- .idea/codeStyles/Project.xml
- server/src/main/resources/log4j2.xml
Fixes #1 
Also added XML indent size code style.
> Improve log rollover.

- reducer/src/main/java/com/graphicsfuzz/reducer/glslreducers/MasterPlan.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/FoldConstantReductionOpportunities.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/IReductionOpportunityFinder.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunities.java
- reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/FoldConstantReductionOpportunitiesTest.java
This change introduces some simple reduction passes that do constant folding, which should help in understanding reduced references and variants.
> Constant folding in reduction

- ast/pom.xml
- client-tests/pom.xml
- common/pom.xml
- fuzzerserver/pom.xml
- generate-and-run-shaders/pom.xml
- generator/pom.xml
- parent-all/pom.xml
- parent-checkstyle/pom.xml
- reducer/pom.xml
- server-public/pom.xml
- server-thrift-gen/pom.xml
- server/pom.xml
- shadersets-util/pom.xml
- tester/pom.xml
- tool/pom.xml
to analyze dependencies during builds. Fixed dependency issues.
> Add maven-dependency-plugin:analyze-all

- server/src/main/java/com/graphicsfuzz/server/webui/WebUi.java
> Show reference result in case of non-SUCCESS

- client-tests/src/test/java/com/graphicsfuzz/clienttests/CommonClientTest.java
- docs/development.md
- generate-and-run-shaders/src/main/java/com/graphicsfuzz/generator/ShaderConsumer.java
- python/src/main/python/drivers/run_shader_family.py
- server-public/src/main/java/com/graphicsfuzz/serverpublic/PublicServerCommandDispatcher.java
- server/src/main/java/com/graphicsfuzz/server/GraphicsFuzzServerCommandDispatcher.java
- server/src/main/java/com/graphicsfuzz/server/webui/WebUi.java
- shadersets-util/src/main/java/com/graphicsfuzz/shadersets/RunShaderFamily.java
- shadersets-util/src/main/java/com/graphicsfuzz/shadersets/RunShaderSet.java
- thrift/src/main/thrift/FuzzerService.thrift
Made run shader set work on a shader job prefix, rather than a .frag shader, and did some renaming of shader set to shader family through the code base (there is still a bit of shader set left; no urgency to fix it everywhere.)
> Rework run shader set

- python/src/main/python/drivers/worker_vk.py
Catch spirv-opt bad behaviors:
- compilation errors
- timeouts (30sec)
> Better spirv opt

- python/src/main/python/drivers/reduce_spirv_opt_flags.py
Added script to find minimal set of spirv-opt flags that triggers an assertion failure.
> Added script to find minimal set of spirv-opt flags that triggers an assertion failure

- reducer/pom.xml
- reducer/src/main/java/com/graphicsfuzz/reducer/ReductionKind.java
- reducer/src/main/java/com/graphicsfuzz/reducer/filejudge/CustomFileJudge.java
- reducer/src/main/java/com/graphicsfuzz/reducer/tool/Reduce.java
- reducer/src/test/java/com/graphicsfuzz/reducer/tool/ReduceTest.java
Support for doing a custom reduction via an external script.
> Support for custom reductions

- ast/src/main/java/com/graphicsfuzz/common/ast/type/SamplerType.java
- ast/src/test/java/com/graphicsfuzz/common/tool/PrettyPrinterVisitorTest.java
The printing of sampler types we had before did not respect case.  The PR fixes this.
> Fixed pretty printing of sampler types.

- common/src/main/java/com/graphicsfuzz/imagetools/ComparePsnr.java
Being able to invoke PSNR directly for reductions or result sanity checking is useful.
> Added standalone tool for PSNR comparison.

- ast/src/main/antlr4/com/graphicsfuzz/parser/GLSL.g4
- ast/src/main/java/com/graphicsfuzz/common/ast/TranslationUnit.java
- ast/src/main/java/com/graphicsfuzz/common/ast/stmt/ExtensionStatement.java
- ast/src/main/java/com/graphicsfuzz/common/ast/stmt/PragmaStatement.java
- ast/src/main/java/com/graphicsfuzz/common/ast/visitors/AstBuilder.java
- ast/src/main/java/com/graphicsfuzz/common/ast/visitors/IAstVisitor.java
- ast/src/main/java/com/graphicsfuzz/common/ast/visitors/StandardVisitor.java
- ast/src/main/java/com/graphicsfuzz/common/tool/PrettyPrinterVisitor.java
- ast/src/test/java/com/graphicsfuzz/common/tool/PrettyPrinterVisitorTest.java
- generator/src/main/java/com/graphicsfuzz/generator/fuzzer/Fuzzer.java
- generator/src/test/java/com/graphicsfuzz/generator/transformation/OpaqueExpressionGeneratorTest.java
- generator/src/test/java/com/graphicsfuzz/generator/transformation/controlflow/SplitForLoopsTest.java
- generator/src/test/java/com/graphicsfuzz/generator/transformation/structifier/StructificationOpportunityTest.java
- reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/InlineStructifiedFieldReductionOpportunityTest.java
Improved support for #version, and added support for #extension and #pragma.
> Support for #extension and #pragma, and better #version support

- ast/src/main/java/com/graphicsfuzz/common/typing/Scope.java
- ast/src/main/java/com/graphicsfuzz/common/typing/ScopeTreeBuilder.java
- common/src/main/java/com/graphicsfuzz/common/util/StripUnusedGlobals.java
- common/src/test/java/com/graphicsfuzz/common/util/StripUnusedGlobalsTest.java
- generator/src/main/java/com/graphicsfuzz/generator/fuzzer/Fuzzer.java
- generator/src/main/java/com/graphicsfuzz/generator/tool/Generate.java
- generator/src/main/java/com/graphicsfuzz/generator/transformation/donation/DonateCode.java
- generator/src/main/java/com/graphicsfuzz/generator/transformation/donation/DonateDeadCode.java
- generator/src/main/java/com/graphicsfuzz/generator/transformation/donation/DonateLiveCode.java
- generator/src/main/java/com/graphicsfuzz/generator/transformation/donation/DonationContext.java
- generator/src/main/java/com/graphicsfuzz/generator/transformation/donation/DonationContexts.java
- generator/src/main/java/com/graphicsfuzz/generator/transformation/injection/AvailableStructsCollector.java
- generator/src/main/java/com/graphicsfuzz/generator/transformation/injection/FreeVariablesCollector.java
- generator/src/test/java/com/graphicsfuzz/generator/fuzzer/FuzzerTest.java
- generator/src/test/java/com/graphicsfuzz/generator/transformation/donation/DonateLiveCodeTest.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/InlineStructifiedFieldReductionOpportunities.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/RemoveStructFieldReductionOpportunities.java
- tester/src/test/java/com/graphicsfuzz/tester/GeneratorUnitTest.java
There were some problems in the generator arising from changes to structs a while ago.  Fixed with tests.
> Fix generator

- ast/src/main/java/com/graphicsfuzz/common/util/TruncateLoops.java
- ast/src/test/java/com/graphicsfuzz/common/util/TruncateLoopsTest.java
- generator/src/main/java/com/graphicsfuzz/generator/transformation/donation/DonateLiveCode.java
- generator/src/test/java/com/graphicsfuzz/generator/transformation/donation/TruncateLoopsTest.java
Changed generation of loop limiters so that they are applied to all loops in live code injection.
> Loop limiters

- checkstyle-config/src/main/resources/graphicsfuzz/checkstyle.xml
- parent-all/pom.xml
See #87 
The old checkstyle plugins might be causing the build to fail on certain configurations. This might help.
> Update checkstyle plugins

- server/src/main/java/com/graphicsfuzz/server/webui/ReductionFilesHelper.java
- server/src/main/java/com/graphicsfuzz/server/webui/WebUi.java
processing/token/shaderfamily_exp/ -->processing/token/shaderfamily/
processing/token/shaderfamily_variant_inv/ --> processing/token/shaderfamily/reductions/variant/
> Rename result directories

- client-tests/src/test/java/com/graphicsfuzz/clienttests/CommonClientTest.java
- common/src/main/java/com/graphicsfuzz/common/util/ShaderJobFileOperations.java
- docs/getting_started.md
- server/src/main/java/com/graphicsfuzz/server/webui/WebUi.java
- shadersets-util/src/main/java/com/graphicsfuzz/shadersets/RunShaderFamily.java
This if for homogeneous capitalization of entries in this JSON, other fields all start with a non-capital letter.
> In JSON of results, de-capitalize "status" entry

- shaders/src/main/glsl/samples/310es/bubblesort_flag.frag
- shaders/src/main/glsl/samples/310es/bubblesort_flag.json
- shaders/src/main/glsl/samples/310es/colorgrid_modulo.frag
- shaders/src/main/glsl/samples/310es/colorgrid_modulo.json
- shaders/src/main/glsl/samples/310es/mandelbrot_blurry.frag
- shaders/src/main/glsl/samples/310es/mandelbrot_blurry.json
- shaders/src/main/glsl/samples/310es/prefix_sum.frag
- shaders/src/main/glsl/samples/310es/prefix_sum.json
- shaders/src/main/glsl/samples/310es/squares.frag
- shaders/src/main/glsl/samples/310es/squares.json
For now, they are just duplicates of the 300es shaders since they don't have #version, but this will probably be the least confusing approach going forward.
> Add 310es shaders

- vulkan-worker/src/common/vulkan_worker.cc
These enable to get an idea of where the worker spends time.
> Add more logging for rough perf measurement

- docs/glsl-fuzz-walkthrough.md
> Document location of default vertex shader

- .gitignore
- .travis.yml
- build/licenses/libpng-LICENSE.txt
- build/travis/1-install-deps-travis.sh
- build/travis/build
- build/travis/build.py
- build/travis/check_headers.py
- build/travis/licenses.py
- graphicsfuzz/src/main/scripts/LICENSE.TXT
- presubmit.sh
Fixes #46. This change also makes various scripts more portable.
> Add presubmit.sh script and make various related changes

- common/src/main/java/com/graphicsfuzz/common/util/StripUnusedGlobals.java
- common/src/test/java/com/graphicsfuzz/common/util/StripUnusedGlobalsTest.java
- generator/src/main/java/com/graphicsfuzz/generator/tool/GenerateShaderFamily.java
Fixes #190 by adding a missing check for whether a struct is referenced by a type constructor expression.
> Struct bugfix

- ast/src/main/antlr4/com/graphicsfuzz/parser/GLSL.g4
- ast/src/main/java/com/graphicsfuzz/common/ast/expr/IntConstantExpr.java
- ast/src/main/java/com/graphicsfuzz/common/ast/expr/UIntConstantExpr.java
- ast/src/test/java/com/graphicsfuzz/common/typing/TyperTest.java
- ast/src/test/java/com/graphicsfuzz/common/util/ParseHelperTest.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/FoldConstantReductionOpportunities.java
- reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/FoldConstantReductionOpportunitiesTest.java
Support for hex and octal parsing.
> Number parsing

- docs/summer-of-code-ideas/2019.md
> Google Summer of Code ideas

- generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
- tester/src/test/java/com/graphicsfuzz/tester/GeneratorUnitTest.java
Adds a new semantics-preserving transformation.
> e -> not not e

- python/src/main/python/drivers/glsl-to-spv-worker.py
- python/src/main/python/drivers/runspv.py
> Add --skip-render to amber worker

- server/src/main/java/com/graphicsfuzz/server/webui/WebUi.java
> Update link URL to point to github repo

- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/Compatibility.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/IReductionOpportunityFinder.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/IdentityMutationReductionOpportunities.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/IdentityMutationReductionOpportunity.java
- reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/IdentityMutationReductionOpportunitiesTest.java
- reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunitiesTest.java
Enhances the reducer so that identity mutations are reduced at the top-level, not only in sub-expressions.
> Reduce identity roots

- server/src/main/java/com/graphicsfuzz/server/webui/WebUi.java
> WebUI: gracefully fail when starting reduction with non-live worker

- docs/android-notes.md
- docs/glsl-fuzz-develop.md
Update Android SDK installation notes. 
Fix #297
> Fix Android documentation

- server/src/main/resources/public/graphicsfuzz.css
> Remove image border in result table

- python/src/main/python/drivers/runspv.py
> runspv: stdout/err to logfile; don't write status twice

- server/src/main/java/com/graphicsfuzz/server/webui/WebUi.java
> Ui remove stage

- server/src/main/java/com/graphicsfuzz/server/webui/WebUi.java
> Add metrics summary data to WebUI.

- python/src/main/python/drivers/glsl-to-spv-worker.py
…ator.  Fixed typo that was preventing compute shaders from running.
> Fix worker for compute, and cleanup of unneeded code

- python/src/main/python/drivers/runspv.py
> Re-enable amber stack trace on Linux with proper timeout killing

- common/src/main/java/com/graphicsfuzz/common/util/ImageUtil.java
Fix #359 Try adding 'V' (HSV) component into histogram comparison.
> histogram comparison: include the V component from HSV

- server/src/main/java/com/graphicsfuzz/server/webui/WebUi.java
- server/src/main/java/com/graphicsfuzz/server/webui/WebUiConstants.java
Fix #347 
WIP as we have to update the URL to point to compute shader documentation.
> WIP Handle compute shader results in UI by pointing to documentation

- reducer/src/main/java/com/graphicsfuzz/reducer/filejudge/CustomFileJudge.java
> CustomFileJudge: directly output stdout/err to log

- generator/src/test/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGeneratorTest.java
Related issue: #411 
Implement the function to declare and assign 1,000 variables to enlarge test coverage.
> Enlarge test in OpaqueExpressionGeneratorTest 

- generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
Related issue: #425 
Add a new case to represent 1 as the exponential function of the opaque zero expression.
> Represent 1 using exp(0.0)

- generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
Implementation #395
Similar to sin
> Add possibility to represent zero as tan of zero vector

- generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
Related issue: #397
Represent 0 as the length of a zero vector.
> Represent 0 as length of a zero vector.

- reducer/src/test/java/com/graphicsfuzz/reducer/util/SimplifyTest.java
Added a test to illustrate issue #110
> Added a test to illustrate limitation in simplifier. 

- reducer/src/test/java/com/graphicsfuzz/reducer/util/SimplifyTest.java
Relate issue: #110
Added possible test cases that remove parentheses after eliminating macros. Further tests will be added once the `Simplify` is updated.
> Add tests for Simplify

- reducer/src/test/java/com/graphicsfuzz/reducer/ReductionDriverTest.java
- reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/RemoveRedundantUniformMetadataReductionOpportunitiesTest.java
Tests to guide in addressing issue #478.
Search for TODO(478) in the code; there are three @Ignored tests.
Once the issue is fixed, these test should be enabled.
> Added tests to guide in addressing issue #478.

- reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/CompoundToBlockReductionOpportunitiesTest.java
> Add a failing test for dead ifs reduce everywhere

- build/travis/release.py
> Add -prerelease flag when making a release

- reducer/src/test/java/com/graphicsfuzz/reducer/util/SimplifyTest.java
Related issue: #110
As suggested by @afd, this PR is intended to minimize the code changed in PR #489.
Updates:
- Add macro wrapper
- Add a missing function name
- Fix space before a comma
> Add macro wrapper and fix space before comma

- build/travis/install-github-release-tool.sh
- build/travis/release.py
> Make releases be draft releases

- reducer/src/test/java/com/graphicsfuzz/reducer/util/SimplifyTest.java
Add test for #491. This can be merged after #489, as this test might end up being redundant.
> Add testIdentityNotNestedRemoved

- checkstyle-config/src/main/resources/graphicsfuzz/checkstyle.xml
- generator/src/main/java/com/graphicsfuzz/generator/tool/Generate.java
- parent-all/pom.xml
- parent-checkstyle/pom.xml
- reducer/src/main/java/com/graphicsfuzz/reducer/ReductionDriver.java
- reducer/src/main/java/com/graphicsfuzz/reducer/glslreducers/SystematicReductionPass.java
- reducer/src/main/java/com/graphicsfuzz/reducer/tool/GlslReduce.java
- test-util/src/main/java/com/graphicsfuzz/common/util/CheckUtilityClass.java
> Update a few maven plug-in versions and fix some warnings

- generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateCodeTransformation.java
- generator/src/test/java/com/graphicsfuzz/generator/transformation/DonateLiveCodeTransformationTest.java
> Fixed issue where attempts to make array access in donated code in bounds were being thwarted

- ast/src/test/java/com/graphicsfuzz/common/ast/stmt/ForStmtTest.java
> Add additional tests for empty for statements

- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/CompoundToBlockReductionOpportunities.java
- reducer/src/test/java/com/graphicsfuzz/reducer/ReductionDriverTest.java
- reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/CompoundToBlockReductionOpportunitiesTest.java
Related issue: #482 
Add an opportunity for the dead if and fixed failed tests.
> Add if_dead opportunities and fix fail tests

- generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
> Add new transformation for rewriting nonscalars as their constructors

- generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
> Fix matrix constructors generating identities for the wrong base type

- ast/src/main/java/com/graphicsfuzz/common/ast/type/BasicType.java
- generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
> Enhance matrix constructor identity to potentially use all elements of matrix

- ast/src/main/java/com/graphicsfuzz/common/ast/type/BasicType.java
- generator/src/main/java/com/graphicsfuzz/generator/fuzzer/templates/VectorMatrixIndexExprTemplate.java
> Remove pointless static numColumns function

- reducer/src/main/java/com/graphicsfuzz/reducer/ReductionDriver.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/IReductionOpportunityFinder.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunities.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/VariableDeclToExprReductionOpportunities.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/VariableDeclToExprReductionOpportunity.java
- reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/VariableDeclToExprReductionOpportunitiesTest.java
Related issue #480:
Implemented new reducer that will replace variable declarations with the binary expressions.
> Implementation: Reducer Opportunity to replace variable declaration with an expression

- ast/src/main/java/com/graphicsfuzz/common/ast/type/BasicType.java
- generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
> Add new identities for integer types that use bitwise operations

- python/src/main/python/drivers/shader-job-to-spirv-fuzz-format.py
- python/src/main/python/drivers/shader-job-uniforms-to-spirv-fuzz-facts.py
Looks through the uniform information in a .json file and produces a corresponding .facts file with protobufs JSON for the spirv-fuzz tool to consume.
> Script to convert GraphicsFuzz uniform information into spirv-fuzz facts

- common/src/main/java/com/graphicsfuzz/common/util/ShaderJobFileOperations.java
- python/src/main/python/drivers/glsl-to-spv-worker.py
- server/src/main/java/com/graphicsfuzz/server/webui/WebUi.java
- server/src/main/resources/public/graphicsfuzz.css
This PR adds some basic support for viewing compute shader results in the WebUI.  It does not yet allow reductions to be kicked off from there, but you can at least browse crashes and mismatches.
> Compute shaders in WebUI

- ast/src/main/java/com/graphicsfuzz/common/typing/TyperHelper.java
Related issue: #464
This PR is simply refactoring the built-in functions by moving all geometric functions into the new method.
> Refactor geometric builtins

- python/src/main/python/drivers/graphicsfuzz_piglit_converter.py
> Fix piglit converter script not inserting GL ES version

- python/src/main/python/drivers/convert-shaders-to-spirv-fuzz-form.py
- python/src/main/python/drivers/graphicsfuzz_tool.py
- python/src/main/python/drivers/runspv.py
- python/src/main/python/drivers/shader_job_uniforms_to_spirv_fuzz_facts.py
In the process refactored runspv a bit in order to reuse parts of it.
> Add script to convert a directory of glsl-fuzz shaders into a form suitable for use with spirv-fuzz.

- python/src/main/python/drivers/gapidfuzz.py
- python/src/main/python/drivers/gfuzz_common.py
- python/src/main/python/drivers/glsl-to-spv-worker.py
- python/src/main/python/drivers/graphicsfuzz_piglit_converter.py
- python/src/main/python/drivers/inspect_compute_results.py
> Refactor common python script functions into one common lib

- server/src/main/java/com/graphicsfuzz/server/webui/WebUi.java
> Fix WebUi paths so variant image shows in wrong image result view

- docs/piglit-worker.md
> docs: Add documentation for piglit worker

- python/src/main/python/drivers/gfuzz_common.py
- python/src/main/python/drivers/piglit-worker.py
Fixes #628 and #629. I was going to separate these into two PRs, but since Paul is gone this week it'd be better to not have merge issues later.
> Piglit worker improvements

- docs/glsl-reduce.md
> Fix URL referring to glsl-fuzz-reduce

- generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
Fixes #640. The fuzzed expression in the clamp will actually be used in execution, so I instead decided to use identity expressions as the shift value, which will always be well-defined and will lead to only marginally less complication than the clamped expression.
> Refactor shift opaque to use identities instead of fuzzed clamped expressions

- generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
> Add function to generate opaque zero/one from dot product of two vectors

- ast/src/main/java/com/graphicsfuzz/common/ast/type/BasicType.java
- generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
- generator/src/main/java/com/graphicsfuzz/generator/transformation/ExpressionIdentity.java
> Added identity to double transpose a matrix

- ast/src/main/java/com/graphicsfuzz/common/ast/type/BasicType.java
- generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
> Add function to make opaque zero/one from determinant of a matrix

- ast/src/main/java/com/graphicsfuzz/common/ast/type/BasicType.java
> Refactor transposedMatrixType() to use makeMatrixType()

- shaders/src/main/glsl/samples/310es/binarysearch_tree.frag
- shaders/src/main/glsl/samples/310es/binarysearch_tree.json
Related issue #545:
**binarysearch_tree**
- Implements a binary search tree using an array 
- Insert a new element into the tree
- Search for an element in the tree
- Use a switch statement
- Use a struct data type to be a node of the tree
> New 310es shader - binary search tree 

- shaders/src/main/glsl/samples/310es/quicksort_palette.frag
- shaders/src/main/glsl/samples/310es/quicksort_palette.json
Related issue #545:
**quicksort_palette**
- Perform quick sort
- Use a do ... while loop
- Use a switch statement
- Use a struct data type
> WIP: new 310es shader

- generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
> Add identity to multiply rectangular matrix/vector by identity matrix

- generator/src/main/java/com/graphicsfuzz/generator/transformation/donation/MakeArrayAccessesInBounds.java
- generator/src/test/java/com/graphicsfuzz/generator/transformation/donation/MakeArrayAccessesInBoundsTest.java
> Fix making array accesses inbounds with uint index accesses

- generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
> Add function to make opaque zero vec3 from cross product of equal vec3s

- generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
> Fix opaque dot function inverted isZero indices

- gfauto/.flake8
- gfauto/.idea/runConfigurations/pytest.xml
- gfauto/.idea/scopes/python_files.xml
- gfauto/Pipfile
- gfauto/Pipfile.lock
- gfauto/README.md
- gfauto/check_all.sh
- gfauto/fix_all.sh
- gfauto/gfauto/signature_util.py
- gfauto/gfautotests/__init__.py
- gfauto/gfautotests/test_signature_util.py
- gfauto/run_protoc.sh
- gfauto/whitelist.dic
Also, add pytest tests and related changes.
> gfauto: fix signature_util plus tests

- ast/src/main/antlr4/com/graphicsfuzz/parser/GLSL.g4
> Apply small fix to GLSL grammar

- gfauto/README.md
- gfauto/gfauto/artifact_util.py
- gfauto/gfauto/fuzz.py
Fix #719 use separate donors and references directories 
Fix #721 iteration_seed == 0 does not work 
Fix #722 add option to skip writing default recipes
> gfauto: fix some issues with parallel running of gfauto

- docs/summer-of-code-ideas/summer-of-code-reports/gsoc-2019-abelbriggs.md
Report detailing work done during Google Summer of Code.
> Google Summer of Code 2019 Report - Abel Briggs 

- gfauto/gfauto/signature_util.py
> gfauto: update signature_util.py

- gfauto/gfauto/android_device.py
- gfauto/whitelist.dic
> gfauto: better handle Android device reboot

- gfauto/README.md
- gfauto/gfauto/binaries_util.py
- gfauto/gfauto/fuzz_glsl_test.py
- gfauto/gfauto/fuzz_spirv_test.py
- gfauto/gfauto/gfauto_interestingness_test.py
- gfauto/gfauto/glsl_generate_util.py
- gfauto/gfauto/result_util.py
- gfauto/gfauto/signature_util.py
- gfauto/gfauto/spirv_fuzz_util.py
- gfauto/gfauto/test_util.py
- gfauto/gfauto/tool.py
- gfauto/whitelist.dic
> gfauto: add GLSL wrong image support

- gfauto/gfauto/fuzz_spirv_test.py
...for much better crash reductions.
> gfauto: add spirv-reduce support

- generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateCodeTransformation.java
This change makes all array accesses of a donor shader be clamped to
be in-bounds as soon as the shader is parsed.
Fixes #778.
> Always make array accesses in bounds during code donation

- generator/src/main/java/com/graphicsfuzz/generator/tool/PrepareReference.java
> Add braces when preparing reference

- gfauto/gfauto/run_cts_gf_tests.py
Also, fix bug where SwiftShader results were incorrect.
> gfauto: run_cts_gf_tests: support android and host

- shaders/src/main/glsl/samples/310es/stable_colorgrid_modulo.frag
- shaders/src/main/glsl/samples/310es/stable_colorgrid_modulo.json
> Stable version of colorgrid modulo.

- shaders/src/main/glsl/samples/310es/stable_mergesort.frag
- shaders/src/main/glsl/samples/310es/stable_mergesort.json
> Stable version of mergesort shader.

- generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
We compute 1.0 as the length of a normalized vector.  Round-off might
mean that we get a result slightly different from 1.0.  This change
introduces a call to 'round', so we compute 1.0 as
'round(length(normalize(non_zero_vector)', to guard against this.  The
use of 'round' means that the transformation is only applicable for
GLSL versions that support 'round'.
> Apply rounding to length of normalized vector

- shaders/src/main/glsl/samples/310es/stable_quicksort.frag
- shaders/src/main/glsl/samples/310es/stable_quicksort.json
> Stable version of quicksort shader.

- build/travis/python-launch.bat
- graphicsfuzz/src/main/scripts/examples/glsl-reduce-walkthrough/fake_compiler.bat
- graphicsfuzz/src/main/scripts/examples/glsl-reduce-walkthrough/interestingness_test.bat
- graphicsfuzz/src/main/scripts/examples/glsl-reduce-walkthrough/weak_interestingness_test.bat
- python/src/main/python/drivers/backtrace-summary.bat
- python/src/main/python/drivers/gapidfuzz.bat
- python/src/main/python/drivers/glsl-generate.bat
- python/src/main/python/drivers/glsl-reduce.bat
- python/src/main/python/drivers/glsl-server.bat
- python/src/main/python/drivers/glsl-to-spv-worker.bat
- python/src/main/python/drivers/graphicsfuzz-piglit-converter.bat
- python/src/main/python/drivers/graphicsfuzz-tool.bat
- python/src/main/python/drivers/inspect-compute-results.bat
- python/src/main/python/drivers/knownvalue-shader-generator.bat
- python/src/main/python/drivers/piglit-worker.bat
- python/src/main/python/drivers/report-compute-shader-family-results.bat
- python/src/main/python/drivers/run-shader-family.bat
- python/src/main/python/drivers/runspv.bat
- python/src/main/python/interestingness/compute-interesting-diff.bat
- python/src/main/python/interestingness/compute-interesting-same.bat
> Fix .bat launchers

- gfauto/gfauto/binaries_util.py
- gfauto/gfauto/fuzz.py
- gfauto/gfauto/fuzz_glsl_test.py
- gfauto/gfauto/fuzz_spirv_test.py
Also add host_preprocessor device automatically if it does not already exist.
> gfauto: add amber binaries to test.json

- gfauto/.gitattributes
...to hide generated files in the GitHub PR interface.
> gfauto: add .gitattributes file

- gfauto/gfauto/fuzz_glsl_test.py
- gfauto/gfautotests/test_large.py
Include a "reduced_stage_one" directory in the summary directory to retain the test after just semantics preserving reduction.
> gfauto: "reduced_stage_one" in summary

- checkstyle-config/src/main/resources/graphicsfuzz/checkstyle.xml
- common/src/main/java/com/graphicsfuzz/common/util/GloballyTruncateLoops.java
- common/src/main/java/com/graphicsfuzz/common/util/UpgradeShadingLanguageVersion.java
- generator/src/main/java/com/graphicsfuzz/generator/tool/GenerateShaderFamily.java
- server/src/main/java/com/graphicsfuzz/server/webui/WebUi.java
Adds spaces after a couple of commas.
> Fix style issues

- ast/src/main/java/com/graphicsfuzz/common/typing/Typer.java
- ast/src/main/java/com/graphicsfuzz/common/util/OpenGlConstants.java
- ast/src/test/java/com/graphicsfuzz/common/typing/TyperTest.java
- generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateCodeTransformation.java
This adds support for the gl_FrontFacing builtin in fragment shaders.
> Add support for gl_FrontFacing builtin.

- ast/src/main/java/com/graphicsfuzz/common/ast/type/StructDefinitionType.java
- ast/src/test/java/com/graphicsfuzz/common/ast/type/StructDefinitionTypeTest.java
Adds a notion of equality between struct definition types.
> Equality for struct definition types

- generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateCodeTransformation.java
Code cleaup to get rid of a parameter that is not used.
> Remove unused parameter

- generator/src/main/java/com/graphicsfuzz/generator/semanticspreserving/AddSwitchMutation.java
- generator/src/test/java/com/graphicsfuzz/generator/semanticspreserving/AddSwitchMutationFinderTest.java
Fixes an issue where introducing switch statements could lead to the
fuzzing of invalid statements when a switch was introduced at the
start of a for loop body: variables introduced by the for loop were
not being considered in the scope of variables available to the
fuzzer, creating a problem if they shadowed variables of different
types that the fuzzer might then use.
> Handle for loop name shadowing when introducing switch statements

- gfauto/gfauto/android_device.py
The timestamp passed to adb logcat to avoid seeing old log messages must be _later_ than the last observed timestamp, otherwise the last observed event may be included. We avoid this issue by concatenating a "9" onto the end of the last observed timestamp.
> gfauto: tweak logcat clear again

- gfauto/gfauto/cov_util.py
Support for gcc 9+ was broken, as it had never been tested. The JSON output from gcov is all on one line, so processing line-by-line is not possible. Instead, we now just parse the JSON using `json.loads(...)`.
> gfauto_cov: fix gcc 9+ support

- reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/StmtReductionOpportunitiesTest.java
> Test for loop limiter reduction issue

- gfauto/gfauto/generate_cts_test_template.py
- gfauto/gfauto/tool.py
Update copyright year in generate_cts_test_template.py. Also, enforce that the short description does not end in a period.
> gfauto: update generate_cts_test_template.py

- gfauto/gfauto/cov_merge.py
- gfauto/gfautotests/test_cov_merge.py
> gfauto: fix cov_merge.py; add test

- gfauto/gfauto/cov_util.py
Use the "current_working_directory" property from gcov to get more accurate source file paths.
> coverage: improve source file paths

- gfauto/gfauto/tool.py
Fix so that spirv-opt receives the common_spirv_args.
> gfauto: pass common args to spirv-opt

- experiments/build-Imagination_Vulkan.sh
- experiments/build-Khronos_Samples_Vulkan.sh
* Khronos Samples
* Imagination Demos
> Add build scripts for Vulkan Khronos Samples and Imagination Demos

- reducer/src/main/java/com/graphicsfuzz/reducer/glslreducers/SystematicReductionPassManager.java
Fix so that some pass lists can be empty.
> Fix to SystematicReductionPassManager.java

- gfauto/README.md
- gfauto/gfauto/fuzz.py
And update README.md with respect to creating a fixed list of seeds.
> gfauto: add iteration limit

- .idea/runConfigurations/Run_reducer.xml
- .idea/runConfigurations/Run_server.xml
Also remove some redundant stuff from Run_server.xml.
> Add "Run reducer" IntelliJ configuration

- gfauto/gfauto/amber_converter.py
"found by GraphicsFuzz." -> "found by the GraphicsFuzz project."
> gfauto: change Amber comment

- shaders/src/main/glsl/samples/320es/stable_mergesort.frag
- shaders/src/main/glsl/samples/320es/stable_mergesort.json
Removes an unused uniform - resolution - from a shader.
> Remove unused uniform

- gfauto/.flake8
- gfauto/.gitignore
- gfauto/dev_shell.sh.template
- gfauto/gfauto/generate_cts_test_template.py
- gfauto/whitelist.dic
Update generate_cts_test_template.py to have better defaults and more accurate comments for most future tests.
> gfauto: update generate_cts_test_template

- gfauto/docs/coverage.md
Add some brief introductory text and add some comments.
> cov: add some details to coverage.md

- common/src/test/java/com/graphicsfuzz/common/util/PipelineInfoTest.java
… pipelineinfo object has been cloned.
TODO(#1054)
> Add test to expose bug in PipelineInfo

- reducer/src/main/java/com/graphicsfuzz/reducer/glslreducers/SystematicReductionPassManager.java
- reducer/src/test/java/com/graphicsfuzz/reducer/ReductionDriverTest.java
…in a more fine-grained fashion.
TODO(#1049)
> Fix bug in reducer

- docs/summer-of-code-ideas/summer-of-code-reports/gsoc-2020-andreperezmaselco.md
Report describing the work done during Google Summer of Code 2020.
> GSoC 2020 report: André Perez Maselco

- docs/summer-of-code-ideas/summer-of-code-reports/gsoc-2020-nipungarg.md
This is the report for the GSoC 2020 project: New Vulkan Samples to Extend Vulkan API Coverage.
> GSoc 2020 report: Nipun Garg

- ast/src/main/java/com/graphicsfuzz/common/tool/PrettyPrinterVisitor.java
- ast/src/test/java/com/graphicsfuzz/common/tool/PrettyPrinterVisitorTest.java
- common/src/main/java/com/graphicsfuzz/common/util/PipelineUniformValueSupplier.java
> Use defines for literal-uniform array elements

- gfauto/docs/coverage.md
Add another example to `gfauto/docs/coverage.md`.
> Add another coverage example

- gfauto/gfauto/android_device.py
- gfauto/gfauto/run_amber_android.py
- gfauto/setup.py
Adds gfauto_run_amber_android to easily run .amber files on Android devices.
> gfauto: Add run_amber_android

- gfauto/gfauto/amber_converter.py
This change moves the texture generation out of the
jobs loop.
> gfauto: only generate texture once

- gfauto/gfauto/fuzz.py
Always delete temp directories, unless --keep_temp flag is passed to gfauto_fuzz. Previously, --iteration_seed would preserve temp directories, which was useful for debugging, but bad when trying to perform repeatable experiments.
> gfauto: add --keep_temp flag

- gfauto/gfauto/signature_util.py
- gfauto/gfautotests/test_signature_util.py
Improve signature extraction for some desktop drivers when using addr2line. Added tests.
> gfauto: improve signatures

- gfauto/gfauto/process_seeds.py
- gfauto/gfautotests/test_signature_util.py
Processes log files and a list of seeds to output the crash signatures obtained by chunks of seeds.
> gfauto: add process_seeds.py

- .github/workflows/gfauto.yml
- .github/workflows/graphicsfuzz.yml
- gfauto/gfauto/cov_to_lines.py
- gfauto/gfauto/split_seeds.py
cov_to_lines: outputs lines covered by input .cov files.
split_seeds: splits a seeds.txt file into several chunks (output .txt files).
> gfauto: add some scripts

- gfauto/gfauto/fuzz_glsl_test.py
- gfauto/gfauto/fuzz_spirv_test.py
- gfauto/gfauto/generate_amber.py
- gfauto/setup.py
Adds generate_amber script, which generates an AmberScript test from a shader job.
> gfauto: add generate_amber

- ast/src/main/java/com/graphicsfuzz/common/ast/expr/LengthExpr.java
- ast/src/main/java/com/graphicsfuzz/common/ast/expr/MemberLookupExpr.java
- ast/src/main/java/com/graphicsfuzz/common/ast/visitors/AstBuilder.java
- ast/src/main/java/com/graphicsfuzz/common/ast/visitors/IAstVisitor.java
- ast/src/main/java/com/graphicsfuzz/common/ast/visitors/StandardVisitor.java
- ast/src/main/java/com/graphicsfuzz/common/tool/PrettyPrinterVisitor.java
- ast/src/main/java/com/graphicsfuzz/common/typing/Typer.java
- ast/src/test/java/com/graphicsfuzz/common/ast/expr/LengthExprTest.java
- ast/src/test/java/com/graphicsfuzz/common/ast/expr/MemberLookupExprTest.java
- ast/src/test/java/com/graphicsfuzz/common/tool/PrettyPrinterVisitorTest.java
- ast/src/test/java/com/graphicsfuzz/common/typing/TyperTest.java
- ast/src/test/java/com/graphicsfuzz/common/util/ParseHelperTest.java
> Support length expressions.

- ast/src/main/java/com/graphicsfuzz/common/ast/type/Std140LayoutQualifier.java
- ast/src/main/java/com/graphicsfuzz/common/ast/visitors/AstBuilder.java
Updates the AST builder and adds a class for the qualifier.
> Add support for std140 qualifier

- common/src/main/java/com/graphicsfuzz/common/util/CannedRandom.java
- common/src/main/java/com/graphicsfuzz/common/util/IRandom.java
- common/src/main/java/com/graphicsfuzz/common/util/RandomWrapper.java
- common/src/main/java/com/graphicsfuzz/common/util/SameValueRandom.java
- common/src/main/java/com/graphicsfuzz/common/util/ZeroCannedRandom.java
- generator/src/test/java/com/graphicsfuzz/generator/semanticschanging/Expr2BinaryMutationFinderTest.java
- reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/UnwrapReductionOpportunitiesTest.java
- tester/src/test/java/com/graphicsfuzz/tester/MiscellaneousGenerateThenReduceTest.java
Update random generators to support long generation and bounded
integers.
> Update random generators

- gfauto/gfauto/amber_converter.py
This change updates gfauto to read the framebuffer size from shader.json
when generating AmberScript.
> gfauto: read the framebuffer size from shader.json

- ast/src/main/java/com/graphicsfuzz/common/glslversion/CompositeShadingLanguageVersion.java
- ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl100.java
- ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl110.java
- ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl420.java
- ast/src/main/java/com/graphicsfuzz/common/glslversion/ShadingLanguageVersion.java
- ast/src/test/java/com/graphicsfuzz/common/typing/TyperTest.java
- build/travis/check_headers.py
- reducer/src/main/java/com/graphicsfuzz/reducer/ReductionDriver.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/IReductionOpportunityFinder.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunities.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/RemoveSwizzleReductionOpportunities.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/RemoveSwizzleReductionOpportunity.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ShortenSwizzleReductionOpportunities.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ShortenSwizzleReductionOpportunity.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/SimplifySwizzleReductionOpportunities.java
- reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/SimplifySwizzleReductionOpportunity.java
- reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/RemoveSwizzleReductionOpportunitiesTest.java
- reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/ShortenSwizzleReductionOpportunitiesTest.java
- reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/SimplifySwizzleReductionOpportunitiesTest.java
Adds support for simplifying, shortening and removing swizzles.
Part of #1179.
> Support for swizzles in the reducer
