common-util/src/main/java/com/graphicsfuzz/common/util/FileHelper.java
common/src/main/java/com/graphicsfuzz/common/util/ReductionProgressHelper.java
reducer/src/main/java/com/graphicsfuzz/reducer/IReductionState.java
reducer/src/main/java/com/graphicsfuzz/reducer/IReductionStateFileWriter.java
reducer/src/main/java/com/graphicsfuzz/reducer/ReductionDriver.java
reducer/src/main/java/com/graphicsfuzz/reducer/filejudge/ImageShaderFileJudge.java
reducer/src/main/java/com/graphicsfuzz/reducer/glslreducers/GlslReductionState.java
reducer/src/main/java/com/graphicsfuzz/reducer/glslreducers/GlslReductionStateFileWriter.java
reducer/src/main/java/com/graphicsfuzz/reducer/glslreducers/SimplePlan.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/LiveOutputVariableWriteReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/tool/Reduce.java
reducer/src/main/java/com/graphicsfuzz/reducer/tool/ReducerBugPoint.java
reducer/src/test/java/com/graphicsfuzz/reducer/ReductionDriverTest.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/UnwrapReductionOpportunitiesTest.java
server/src/main/java/com/graphicsfuzz/server/webui/ReductionFilesHelper.java
server/src/main/java/com/graphicsfuzz/server/webui/WebUi.java
tester/src/test/java/com/graphicsfuzz/tester/ReducerUnitTest.java

The tool chain has traditionally been very fragment shader centric, as we used to deal exclusively with fragment shaders.  This refactoring makes the reducer less fragment shader centric by (a) having a reduction work on a *prefix* of the name of the shader or shaders being reduced (i.e., "foo" rather than "foo.frag"), and (b) having GlslReductionState encapsulate either/both of a vertex and fragment shader as well as uniforms info.
There is more to be done but this is a good first chunk to merge.

Refactor reducer

---

CONTRIBUTORS

which includes Donaldson, Evrard and Thomson due to their pre-Google contributions.

Added Imperial contributors

---

python/src/main/python/drivers/worker_vk.py

When several devices are plugged in the same server, we can easily forget to set ANDROID_SERIAL, which results in a list of irrelevant crashes.

Impose usage of Android serial number

---

assembly-public/pom.xml
assembly/pom.xml
build/travis/licenses.py
common/pom.xml
parent-all/pom.xml
server/pom.xml
third_party/alphanum-comparator/pom.xml
third_party/gif-sequence-writer/pom.xml
third_party/jquery-js/pom.xml
third_party/semantic-ui/pom.xml
third_party/thrift-js/pom.xml
third_party/thrift-py/pom.xml

Third party internal maven projects now use group com.graphicsfuzz.thirdparty. The group com.graphicsfuzz is now ignored by the licenses.py script so we don't need to provide license information for our own maven projects.

Fixes #45.

---

vulkan-worker/src/common/vkcheck.cc
vulkan-worker/src/common/vkcheck.h
vulkan-worker/src/common/vulkan_worker.cc

Log function calls before and after actually calling them. This clarify which function call actually triggers a crash.

Improve logging macros

---

vulkan-worker/src/android/src/main/cpp/main.cc
vulkan-worker/src/common/vulkan_worker.cc
vulkan-worker/src/common/vulkan_worker.h
vulkan-worker/src/linux/main.cc

A few optimizations to avoid re-creating a graphics pipeline when rendering the same shaders several times in a row. Also, the command buffers for exporting the image are created once, and not every time we want to export an image.
This lead to a performance gain of 500ms, from 1700ms to 1200ms, on an typical example.

Prepare command buffers only once for several renderings and exports

---

assembly-binaries/pom.xml
parent-all/pom.xml
pom.xml
zip-helper/pom.xml
zip-helper/src/main/java/com/graphicsfuzz/zip/ZipArchiveEntrySettableName.java
zip-helper/src/main/java/com/graphicsfuzz/zip/ZipFromZip.java

Created an executable utility that creates zips from zips, retaining file permissions. Use it in build instead of Ant zip task.

Fix binary permissions.

---

python/src/main/python/drivers/vkrun.py

I've seen weird situtations on the Shield where the adb pull did not retrieve all images, or maybe some images were not even being produced. This fix avoids to crash the worker, and have to restart it again by hand, in such a case.

Do not assume all images are actually produced/retrieved

---

vulkan-worker/src/android/src/main/cpp/main.cc

It used to be a plain assertion failure, now we produce a better error message in the log.
Fix #124 . We could do a better job by using Java, but it would add a huge amount of code.

Fail when missing external storage permission

---

python/src/main/python/drivers/glsl-to-spv-worker.py
python/src/main/python/drivers/vkrun.py

Add all plumbing in vkrun.py and glsl-to-spv-worker.py to render tests using vkrunner.

Add vkrunner backend for SPIRV worker

---

python/src/main/python/drivers/glsl-to-spv-worker.py
python/src/main/python/drivers/vkrun.py

These are minimal changes to get compute shader support via VkRunner.
It assumes SSBO and shader to operate on `int` type of 32 bits. It also assume the device in little endian (which is the case of virtually all device). The resulting SSBO values are provided in the '.info.json' file as:
` { [...], "outputs": { "ssbo": [1,2,3, ... ] } }`
There will be refactor once we have a better understanding of how we want to handle compute shaders, e.g. how to handle different types in SSBO, or resulting values.

Add minimal support for compute shaders

---

generator/src/main/java/com/graphicsfuzz/generator/tool/GenerateShaderFamily.java
generator/src/test/java/com/graphicsfuzz/generator/tool/GenerateShaderFamilyTest.java

Provides options for disabling shader_translator and/or glslangValidator.  Allows us to work around limitations in these tools if needed.

Allow disabling validation

---

ast/src/main/java/com/graphicsfuzz/common/ast/TranslationUnit.java
common/src/main/java/com/graphicsfuzz/common/transformreduce/GlslShaderJob.java

Fixed pretty-printing of for loop with empty header, and removed some assumptions about available precision that were being made when 'injectionSwitch' or structs were added.

Fixes issues that were blocking handling of shaders in the wild.

---

common/pom.xml
common/src/main/java/com/graphicsfuzz/common/util/ImageUtil.java
parent-all/pom.xml
tool/pom.xml

Also update opencv. This fixes #164, although it would still be good to consider other image comparison algorithms.

Add alpha channel support for histogram comparison

---

common/src/main/java/com/graphicsfuzz/common/util/FuzzyImageComparison.java
common/src/main/java/com/graphicsfuzz/common/util/ImageUtil.java
common/src/main/java/com/graphicsfuzz/common/util/ShaderJobFileOperations.java
common/src/main/java/com/graphicsfuzz/shadersets/IImageFileComparator.java
common/src/main/java/com/graphicsfuzz/shadersets/MetricImageFileComparator.java
reducer/src/main/java/com/graphicsfuzz/reducer/tool/GlslReduce.java
server/src/main/java/com/graphicsfuzz/server/webui/WebUi.java
server/src/main/resources/public/graphicsfuzz.css
server/src/main/resources/public/graphicsfuzz.js
thrift/src/main/thrift/FuzzerService.thrift
tool/src/main/java/com/graphicsfuzz/tool/FuzzyImageComparisonTool.java

Fix #283 
* Make FuzzyImageComparison.MainResult serializable to JSON and to a summary output string.
* Add FUZZY_DIFF as a metric type. 
* Update help of glsl-reduce for FUZZY_DIFF metric, plus add some examples. Also add these "hints" to the WebUI. 
* Add CSS for "metrics disagree".
* Small fix to identicalImages function (mostly unrelated fix).
* Add fuzzy diff metric to the metrics in .info.json files and simplify this code.
* WebUI: replace image comparison methods with one method and refactor. Use fuzzy diff algorithm and support "metrics disagree" result.
* Make fuzzy diff the default algorithm in the reducer and WebUI. 
* Update WebUI reduction page.

Integrate fuzzy comparison algorithm into reducer and Web UI

---

generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateCodeTransformation.java
generator/src/test/java/com/graphicsfuzz/generator/tool/GenerateShaderFamilyTest.java

Added shader family test to expose issues with layout qualifiers being applied to local variables during donation, and fixed this problem.

Strip layout qualifiers during donation

---

server/src/main/java/com/graphicsfuzz/server/webui/WebUi.java
server/src/main/resources/public/graphicsfuzz.css

The legend only shows up in pages which have a result table.
NOTE: this change revealed that some colors were too close to each other, so I also updated the colors.
The legend looks like this:

Document colors of result tables with a legend in the UI

---

python/src/main/python/drivers/runspv.py

runspv: fix timeout handling

---

python/src/main/python/drivers/runspv.py

Probably fix #306 (amber desktop error messages are not captured)
Probably fix #301
stdout and stderr are now captured by default (but not printed, as this is too verbose). We print the command and returncode, which is helpful for understanding what runspv is doing. "check=True" by default.

runspv: improve subprocess_helper

---

ast/src/main/java/com/graphicsfuzz/common/ast/inliner/ReturnRemover.java
ast/src/main/java/com/graphicsfuzz/common/ast/stmt/DoStmt.java
ast/src/main/java/com/graphicsfuzz/common/ast/stmt/ForStmt.java
ast/src/main/java/com/graphicsfuzz/common/ast/stmt/LoopStmt.java
ast/src/main/java/com/graphicsfuzz/common/ast/stmt/WhileStmt.java
ast/src/test/java/com/graphicsfuzz/common/ast/inliner/ReturnRemoverTest.java
ast/src/test/java/com/graphicsfuzz/common/ast/stmt/ForStmtTest.java
generator/src/main/java/com/graphicsfuzz/generator/semanticspreserving/SplitForLoopMutation.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/LoopMergeReductionOpportunity.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunitiesTest.java

This PR hardens up the code base by removing the assumption that a for loop has a condition and an increment.  We have seen shaders in the wild that do not, and some of our compute shader samples do not.

Guard against null pointer exceptions when working with empty for loops

---

python/src/main/python/drivers/runspv.py

Do not try to get the stack trace on Linux. We will revisit this later, see #338 for the discussion.

Remove usage of catchsegv as it is not killed properly in case of timeout

---

python/src/main/python/drivers/glsl-to-spv-worker.py
python/src/main/python/drivers/runspv.py
python/src/main/python/test_scripts/test_runspv/runspv_tests.py

Fix glsl-to-spv-worker and runspv to consistently use the output_dir parameter, instead of (sometimes) writing files to the current directory.
runspv: remove more accidental direct writes to "logfile", instead of using `log('...')`. 
Base output directory on job name.
Clear output directory before start; avoids name clashes from previous results; avoids having to delete individual files that could be missed.
Do not use os.chdir.
Fix skip_render flag for legacy worker on host platform. 
Make `dump_info_host_legacy` just raise an exception if it fails instead of writing to STATUS file; we will catch the exception anyway. 
glsl-to-spv-worker: use `open_helper`. 
Fix #317 files may clash with previously pulled files. 
Fix #352 skip render flag not passed on legacy host. 
Fix #353 some files …

glsl-to-spv-worker: use output_dir and other fixes

---

vulkan-worker/src/common/vulkan_worker.cc

Many PNG decoders will ignore the alpha channel unless the color type is RGBA.
Fixes #364 for our legacy vulkan worker.

vulkan worker: force RGBA color type for PNG output

---

docs/glsl-fuzz-develop.md
docs/glsl-fuzz-generate.md
docs/glsl-fuzz-walkthrough.md
docs/legacy-vulkan-worker.md

Fix #288 
Put the legacy worker documentation aside in `legacy-vulkan-worker.md`.

Update doc to replace legacy worker by runspv and amber

---

reducer/src/test/java/com/graphicsfuzz/reducer/tool/GlslReduceTest.java
util/src/main/java/com/graphicsfuzz/util/ExecHelper.java

I believe files are always considered executable on Windows, so we can skip this test. 
Fix #370

GlslReduceTest.checkCustomJudgeIsExecutable: skip on Windows

---

generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java

Related issue: #399 
Allows sqrt(genType) to be used in place of straight 0/1 floats/vectors when generating shader families.

Use sqrt() in representations of 0 and 1

---

python/src/main/python/drivers/runspv.py

Fix #416
Also use '--raw-id' in spirv-dis to get consistent ids.

runspv: .shader_test files include GLSL as comment

---

ast/src/main/java/com/graphicsfuzz/common/typing/DuplicateVariableException.java
docs/libFuzzer-integration.md
generator/src/main/java/com/graphicsfuzz/generator/tool/CustomMutatorServer.java
generator/src/main/java/com/graphicsfuzz/generator/tool/CustomMutatorSever.java
generator/src/main/java/com/graphicsfuzz/generator/tool/Mutate.java
graphicsfuzz/src/main/scripts/examples/libFuzzer-integration/jni_fuzzer.cc
graphicsfuzz/src/main/scripts/examples/libFuzzer-integration/tcp_fuzzer.cc

This adds a working server that can accept shaders over TCP from a libFuzzer custom mutator and returns a mutated shader.
I've confirmed this works by modifying [ANGLE's translator fuzzer](https://cs.chromium.org/chromium/src/testing/libfuzzer/fuzzers/BUILD.gn?type=cs&q=angle_translator_fuzzer&sq=package:chromium&g=0&l=340) to use this server instead of using libFuzzer's standard mutations.
I still need to figure out how those changes will be upstreamed to ANGLE (I want to do it in a way that doesn't mess things up on ClusterFuzz).
This implementation may be replaced with something faster (e.g. shared memory).
Other details of the implementation will probably change, these include: 
* Currently the server listens on port `8666` and can only accept one connection. This doesn't allow …

Add initial version of libFuzzer custom mutator server

---

generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java

Implemented #398, add a new case in makeOpaqueZeroOrOne to generate 1 as the length of the normalized vector.

Represent 1 as length of normalized vector

---

generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java

Related issue: #394 
Add a new case to represent 1 as the cos() function of the opaque zero expression.

Represent 1 using cos() function

---

generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java

Fixes: #393 
Add a new way of representing 0 as sin(expression) where expression is guaranteed to be also zero.

Represent 0 as sin(0.0)

---

docs/glsl-fuzz-walkthrough.md

While following the walkthrough guide, I couldn't find the sample file paths just after I built the packages. It is true that the current mentioned path also works after carrying out the next step and copying the samples from the extracted zip file but I think using the new path is just easier to find and works in both cases.

Update sample file paths

---

generator/src/main/java/com/graphicsfuzz/generator/fuzzer/Fuzzer.java
generator/src/main/java/com/graphicsfuzz/generator/fuzzer/Templates.java
generator/src/test/java/com/graphicsfuzz/generator/transformation/DonateLiveCodeTransformationTest.java

Makes sure that shading language version used during expression fuzzing does not deviate from the shading language version used by the shader.

Keep shading language version in sync

---

generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java

Related issue: #426 
Add a new case to represent 0 as the log() function of the opaque one expression.

Represent 0 using log(1.0)

---

fuzzerserver/src/main/java/com/graphicsfuzz/server/SingleJob.java

fixes #384 This patch fixes Typo in SeverJobException message
where one space was missing.
Signed-off-by: Vipin Anand <anand.vipin@gmail.com>

fix:Typo in SeverJobException message

---

generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueZeroOneFactory.java

Related issue #427, built-in functions used to generate opaque zero and one expressions are now separated into the different methods.

Seperate functions making opaque 1 and 0

---

generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java

Related issue: #400
Represent 1 and 0 as the absolute value of an opaque expression.

Represent 0 and 1 using abs(opaque)

---

gles-worker/desktop/src/com/graphicsfuzz/glesworker/desktop/DesktopLauncher.java

Related issue: #390
JVM Argument `-XstartOnFirstThread` has been added to prevent an exception thrown by GLFW when running `gles-desktop-work` on Mac.

Add XstartOnFirstThread argument for Mac

---

docs/glsl-fuzz-develop.md

Fix amber path typo for Android.

Fix typo amber_ndk path

---

generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java

Related issue: #474
Rename opaque factory variables in method `waysToMakeOne` and `waysToMakeZero`.

Rename opaque factories variable

---

server/src/main/java/com/graphicsfuzz/server/webui/WebUi.java
server/src/main/java/com/graphicsfuzz/server/webui/WebUiConstants.java

In preparation for some work on the WebUI, here is a bit of renaming of the legacy term 'shaderset' to the more up-to-date term 'shader family'.
The renaming has only been applied to Java classes and variables, comments, and messages in the WebUI.  It has not been applied to the web logic of the WebUI itself.

Renaming of 'shaderset' to 'shader family'

---

common/src/main/java/com/graphicsfuzz/common/util/ShaderJobFileOperations.java

The problem has been fixed in shader_translator.

Remove guard against shader_translator memory exhaustion error

---

graphicsfuzz/pom.xml

Exclude .pdb files from graphicsfuzz.zip

---

reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/RemoveRedundantUniformMetadataReductionOpportunitiesTest.java

The tests check the cases where (a) a uniform is truly unused, but
there is a use of a shadowing variable with the same name, and (b) a
uniform is used in a fragment shader but not vertex shader, and vice
versa.

Added more tests for removing uniforms

---

server/src/main/java/com/graphicsfuzz/server/webui/WebUi.java

A previous refactoring had led to confusion between two variables, one
a file, the other a string, such that the result of calling toString()
on the file was appearing in URLs.

Fix to WebUI to avoid null pointer exception

---

reducer/src/test/java/com/graphicsfuzz/reducer/util/SimplifyTest.java

Related issue: #110
As this [comment](https://github.com/google/graphicsfuzz/pull/489/files#r287494701) addressed, this PR added a test case for checking parentheses removal for the function call expression.

Add e test for function call macro parentheses removal

---

common/src/main/java/com/graphicsfuzz/common/util/ShaderJobFileOperations.java
reducer/src/main/java/com/graphicsfuzz/reducer/ReductionDriver.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/IReductionOpportunityFinder.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/RemoveRedundantUniformMetadataReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/RemoveRedundantUniformMetadataReductionOpportunity.java
reducer/src/test/java/com/graphicsfuzz/reducer/ReductionDriverTest.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/RemoveRedundantUniformMetadataReductionOpportunitiesTest.java

Related issue: #478
Added a new reducer opportunity which removes all redundant uniforms metadata in JSON except for the uniforms that are declared but not used.

Reducer opportunity to remove redundant uniform metadata

---

ast/src/main/java/com/graphicsfuzz/common/ast/stmt/SwitchStmt.java
reducer/src/main/java/com/graphicsfuzz/reducer/glslreducers/EliminateInjectionMacrosVisitor.java
reducer/src/test/java/com/graphicsfuzz/reducer/util/SimplifyTest.java

Related issue: #110 
- Remove the unneeded parentheses that exist after the macros elimination
- Update statement in the test cases that previously do not have the wrapper

Remove parentheses after eliminating macros

---

generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java

As discussed in #254.
The idea behind this is that I only want to generate identities for specific entries in a vector/matrix, and not enclose the whole nonscalar with identities.
To do this;
`v -> (true ? vecX(..., identity(v[Y]), ...) : _)`
`v -> (false ? _ : vecX(..., identity(v[Y]), ...))`
where v is a vector of size X, y is the random entry in v we want to apply
identities to, and ... is the other entries in v that we don't change. The form is the same for matrices, but instead of applying identities to one entry, we'd apply them to one column of the matrix (the syntax is similar).
However, I'm currently running into issues with GenerateShaderFamily tests failing because of aliasing on the AST.
From what I understand of the full stacktrace and through debugging, the test fails while …

Generate ternary identities for nonscalar types

---

ast/src/main/java/com/graphicsfuzz/common/typing/TyperHelper.java

Implements #466.
All versions of GLSL support the nine vector relational functions - the only difference between versions is that they can be used with unsigned integers in GLSL versions 1.3+ and ESSL versions 3.0+ (where uints were added).

Add built-in function support for GLSL Vector Relational Functions

---

ast/src/main/java/com/graphicsfuzz/common/ast/type/BasicType.java

Fixes #531. 
This PR:
- makes a distinction between usage of RuntimeException and UnsupportedOperationException - RuntimeException is still used in functions like toString(), where the type could possibly be in an invalid state. RuntimeException has been replaced by UnsupportedOperationException when the user can potentially (and realistically) misuse a function (sending invalid arguments or using an unintended type). Additionally, UnsupportedOperationException is thrown instead of asserting when an error state is realistically possible.
- adds Javadoc comments to functions that throw UnsupportedOperationException.
- replaces usage of static allTypes().contains(type) calls with the corresponding isType() call when the current scope is not static.

Refactor BasicType with documentation and exception improvements

---

reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/VariableDeclToExprReductionOpportunitiesTest.java

As [suggested](https://github.com/google/graphicsfuzz/pull/529#pullrequestreview-247493203),
This test ensures that the reducer will not consider the `const` variable declaration as the opportunites.

Add test for const variable declaration 

---

ast/src/main/java/com/graphicsfuzz/common/ast/type/BasicType.java
ast/src/main/java/com/graphicsfuzz/common/typing/SupportedTypes.java
generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
generator/src/main/java/com/graphicsfuzz/generator/fuzzer/templates/SwizzleExprTemplate.java
generator/src/main/java/com/graphicsfuzz/generator/fuzzer/templates/VectorMatrixIndexExprTemplate.java
generator/src/main/java/com/graphicsfuzz/generator/semanticspreserving/IdentityMutationFinder.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/FoldConstantReductionOpportunities.java

Fixes #536.
This PR makes the distinction that the isScalar/isVector/isMatrix functions are used whenever we know for certain that the type in question is a BasicType (and can use those methods). Whenever we work with a Type instead of a BasicType (in more general cases, and in most lambda expressions), we can't use those functions.

Refactor code to use isType functions when possible

---

common/src/main/java/com/graphicsfuzz/common/util/SideEffectChecker.java
common/src/test/java/com/graphicsfuzz/common/util/SideEffectCheckerTest.java
generator/src/main/java/com/graphicsfuzz/generator/fuzzer/templates/FunctionCallExprTemplate.java

Fixes #522 and #524. I made sure to test this outside of the IDE by readding built-ins (specifically the integer ones) with out parameters and generating hundreds of variants, then grepping for the offending functions to see if they were being used properly.

Check for side effects with lvalue parameters of built-in functions

---

ast/src/main/java/com/graphicsfuzz/common/glslversion/CompositeShadingLanguageVersion.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl100.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl310.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl110.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl400.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/ShadingLanguageVersion.java
ast/src/main/java/com/graphicsfuzz/common/typing/TyperHelper.java
ast/src/test/java/com/graphicsfuzz/common/typing/TyperTest.java
common/src/test/java/com/graphicsfuzz/common/util/SideEffectCheckerTest.java

Implements what can currently be implemented of #467. There are some functions that cannot be supported yet due to issues #522 and #524.
OpenGL versions including and above 3.1ES and 4.0 support integer functions. The function signatures do not change between versions, nor were any functions added after 3.1ES, so I went ahead and added to the ShadingLanguageVersion interface instead of manually checking all the versions in TyperHelper.
Regarding the change in TyperTest, the test was not set up to handle void-returning functions, producing statements like:
```
uint testwhatever()
{
return imul(u0, u1, u2, u3);
}
```
when imul() is a void function. This would cause a validation error, so I added a void type check.

Add built-in support for GLSL Integer Functions

---

ast/src/main/java/com/graphicsfuzz/common/glslversion/CompositeShadingLanguageVersion.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl100.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl300.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl320.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl110.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl400.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl450.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/ShadingLanguageVersion.java
ast/src/main/java/com/graphicsfuzz/common/typing/TyperHelper.java

Implements #468.
Basic derivative functions (dFdx, dFdy, fwidth) are supported by GLSL 1.1+ and ESSL 3.0+.
Extended derivative functions (coarse and fine versions of the above functions) are supported by GLSL versions 4.5+.
Interpolation functions are supported by GLSL 4.0+ and ESSL 3.2+. I ran into a snag involving these functions that I detailed in issue #550. For now, I've removed them from this PR.

Add built-in function support for GLES 3.20 Fragment Processing Functions

---

ast/src/main/java/com/graphicsfuzz/common/glslversion/CompositeShadingLanguageVersion.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl100.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl300.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl110.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl130.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/ShadingLanguageVersion.java
ast/src/main/java/com/graphicsfuzz/common/typing/TyperHelper.java

Related issue: #460
The implementation of the new set of the built-in function for Angle and Trigonometric Functions. Following are the GLSL supported version for the new built-in functions.
General trigonometric functions (sin, cos, tan, etc):
- GLSL 1.1+
- GLSL ES 1.0+
Hyperbolic trigonometric functions (sinh, cosh, asinh, etc):
- GLSL 1.3+
- GLSL ES 3.0+

Add support for angle and trigonometric built-in functions

---

common/src/main/java/com/graphicsfuzz/common/util/PipelineInfo.java

Fixes #556, whereby some tests would fail under Windows with OpenJDK
due to an attempt to move a file that was still open.

Use try-with-resources to ensure file is closed.

---

ast/src/main/java/com/graphicsfuzz/common/typing/TyperHelper.java

Fixes #461.
The exponential functions are the same across every version of GLSL, so this PR is simply to move the process of adding the exponential builtins to a new function.

Refactor exponential builtins into separate function

---

reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/GlobalVariableDeclToExprReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/GlobalVariableDeclToExprReductionOpportunity.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/GlobalVariableDeclToExprReductionOpportunitiesTest.java

Related issue: #519
Added class skeleton and tests for the reducer to reduce global initializers with the assignment statements.

Reducer: Add class skeleton and tests

---

reducer/src/main/java/com/graphicsfuzz/reducer/filejudge/CustomFileJudge.java
reducer/src/main/java/com/graphicsfuzz/reducer/tool/GlslReduce.java

Fix #572.
Fix #573.
* Improve glsl-reduce help text.
* Allow custom interestingness command to take arguments.
* Run custom interestingness command from current directory.
* Don't pass a second argument (an undocumented output file path) to interestingness test.

Improve custom reduction support.

---

generator/src/main/java/com/graphicsfuzz/generator/tool/PrepareReference.java

The header is not needed, so it is pointless and misleading to
generate it.

Do not generate GraphicsFuzz header when preparing a reference shader.

---

generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java

Fixes #551.
Possibilities added for opaque zero generation:
(opaque zero) >> (0 if signed, otherwise a number between 0 and 1000)
(opaque zero) << (0 if signed, otherwise a number between 0 and 1000)
(opaque zero or one) & (opaque zero)
(opaque zero) & (opaque zero or one)
(opaque zero) | (opaque zero)
(opaque zero) ^ (opaque zero)
(opaque one) ^ (opaque one)
Possibilities added for opaque one generation:
(opaque one) >> 0
(opaque one) << 0
(opaque one) & (opaque one)
(opaque one) | (opaque zero or one)
(opaque zero or one) | (opaque one)
(opaque zero) ^ (opaque one)
(opaque one) ^ (opaque zero)

Add new ways to generate opaque zero/one from bitwise operations

---

python/src/main/python/drivers/graphicsfuzz-piglit-converter
python/src/main/python/drivers/graphicsfuzz-piglit-converter.bat
python/src/main/python/drivers/graphicsfuzz-piglit-converter.py
python/src/main/python/drivers/graphicsfuzz_piglit_converter.py

Fixes #571.
Given a shader job JSON file as an argument (with a corresponding shader file of the same name in the same directory), this script outputs a piglit shader_runner test to the same directory that loads the uniforms in the JSON file, runs the test, and draws the image.
As I don't know how compute shader data is loaded into piglit (and I couldn't find docs on it), this script currently only works for fragment shaders.
My Python is pretty rusty, so feel free to be picky about code review.

Add script to convert a GraphicsFuzz shader job to a piglit shader test

---

generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java

Fixes #579.
While this didn't get caught by the validation tests, it causes undefined/non-determinant behavior when rendering shaders.
This is an example of what was generated:
```
1 << clamp(- 25010, int((injectionSwitch.x)), int(4)) >> clamp(2949, 0, int(4));
```
injectionSwitch.x = 0, so the statement becomes
(1 << 0) >> 4
which is not our intention for producing this opaque one.
I opted to remove the chance to generate a second clamp expression because we don't have any control over what kind of fuzzed value comes out, so we can't safely ensure it'll always evaluate to the same number.

Ensure bitwise shift opaque one shifts left/right by same value

---

ast/src/main/java/com/graphicsfuzz/common/typing/TyperHelper.java

Fix #463.
This PR is simply refactoring the built-in functions by moving all floating-point pack and unpack functions into the new method.

Refactor floating-point pack and unpack built-ins

---

ast/src/main/java/com/graphicsfuzz/common/ast/inliner/Inliner.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/CompositeShadingLanguageVersion.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl100.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl310.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl110.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl430.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/ShadingLanguageVersion.java
ast/src/main/java/com/graphicsfuzz/common/typing/Typer.java
ast/src/main/java/com/graphicsfuzz/common/typing/TyperHelper.java
ast/src/test/java/com/graphicsfuzz/common/typing/TyperTest.java
common/src/main/java/com/graphicsfuzz/common/util/Obfuscator.java
common/src/main/java/com/graphicsfuzz/common/util/SideEffectChecker.java
common/src/test/java/com/graphicsfuzz/common/util/SideEffectCheckerTest.java
generator/src/main/java/com/graphicsfuzz/generator/fuzzer/Fuzzer.java
generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
generator/src/main/java/com/graphicsfuzz/generator/fuzzer/Templates.java
generator/src/main/java/com/graphicsfuzz/generator/semanticschanging/InterchangeExprMutationFinder.java
generator/src/main/java/com/graphicsfuzz/generator/semanticspreserving/AddLiveOutputWriteMutation.java
generator/src/main/java/com/graphicsfuzz/generator/tool/Generate.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateCodeTransformation.java
generator/src/main/java/com/graphicsfuzz/generator/util/RestrictFragmentShaderColors.java
generator/src/test/java/com/graphicsfuzz/generator/transformation/donation/MakeArrayAccessesInBoundsTest.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/CompoundToBlockReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/FoldConstantReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/FunctionReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/InlineStructifiedFieldReductionOpportunity.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunitiesBase.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/SimplifyExprReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/StmtReductionOpportunities.java

Now that we more comprehensively support builtins, we have the problem
that not all builtins are available for every kind of shader.  This
change adds a ShaderKind parameter to the function that produces
available builtins, so that only relevant builtins will be returned.
This has required quite a lot of plumbing through, as sometimes
builtins are asked for at relatively deep points in the code, where
the relevant ShaderKind was not always available.
The tests for validity of builtin functions have been extended to try
not just every shading language version and also every kind of shader;
this would catch the (previously uncaught) problem where a fragment
processing builtin could be generated in a compute shader.
Fixes #588.

Make available builtins aware of shader kind

---

ast/pom.xml
ast/src/main/java/com/graphicsfuzz/common/util/TruncateLoops.java
ast/src/test/java/com/graphicsfuzz/common/util/TruncateLoopsTest.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateLiveCodeTransformation.java

We had functionality that was not used anywhere to avoid adding
limiters to short-running loops, and associated tests for this that
took quite a long time to run.  This change removes that unused
functionality.

Simplify loop limiters

---

reducer/src/test/java/com/graphicsfuzz/reducer/tool/GlslReduceTest.java

A test uses an empty file as a custom interestingness judge.  Due to not having the .bat extension, this would lead to a pop-up on Windows asking what kind of program should be used to open the file.  As other platforms don't care about the file extension of an executable script, this change uses .bat to avoid the pop-up on Windows.
Fixes #557

Avoid pop-up on Windows during testing

---

ast/src/main/java/com/graphicsfuzz/common/glslversion/CompositeShadingLanguageVersion.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl100.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl300.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl310.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl110.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl130.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl400.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/ShadingLanguageVersion.java
ast/src/main/java/com/graphicsfuzz/common/typing/TyperHelper.java
common/src/test/java/com/graphicsfuzz/common/util/SideEffectCheckerTest.java

Related issue: #462 
This PR refactors and adds 3 additional common built-in functions:
- modf GLSL 130+ and ESSL 300+)
- frexp (GLSL 400+ and ESSL 310+)
- ldexp (GLSL 400+ and ESSL 310+)
Tests for side effect are also implemented for `modf` and `frexp` as they have out qualifier parameters.

Complete common builtins

---

python/src/main/python/drivers/glsl-to-spv-worker.py

Related issue: #530 
I frequently use the glsl-to-spv-worker with option ` --local-shader-job` to run the local shader job and have to add the argument locally to fix such error, I thus believe it is worth doing this small fix.

Add an open_helper argument in spv-worker

---

common/src/main/java/com/graphicsfuzz/common/util/SideEffectChecker.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/InjectionTracker.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunitiesBase.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/SimplifyExprReductionOpportunities.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/CompoundToBlockReductionOpportunitiesTest.java

The reducer used to be very conservative about replacing dead code
injections with their bodies and was made less conservative.  However
this introduced a bug whereby the reducer would always replace
'if(_GLF_DEAD(...)) body' by 'body'.  The problem was that the guard
of the dead code injection was being regarded as itself being dead
code, which is wrong; it should only be the 'then' and 'else' branches
of the if statement that are regarded as dead.
This change fixes this problem.  It was necessary to change a number
of tests in the process: tests where the reducer was only managing to
do a particularly good job of reducing a shader due to this bug; for
example it could turn:
if (_GLF_DEAD(...)) {
int a;
a = 2;
}
into:
{
int a;
a = 2;
}
which is OK, because the body of the 'if' statement …

Fix issue where the reducer was replacing a dead code injection with its body

---

generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
generator/src/test/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGeneratorTest.java

We recently added the ability to generate zero as length(zero vector),
and one as length(normalize(one vector)).  However, the code was
incorrectly assuming that the length of a vector of dimension n would
itself be a vector of dimension n, whereas in reality the length of a
vector is always a scalar.
As well as fixing this so that the expected return type for these ways
to make zero and one is 'float', the change allows the dimension of
the vector whose length is taken to be chosen at random.
Finer-grained tests for opaque zero and one generation are also added,
and the shading language versions for which opaque expression
generation is tested has been expanded a bit.
Fixes #559

Fix opaque expressions based on vector length

---

assembly-binaries/pom.xml
tester/src/test/java/com/graphicsfuzz/tester/GeneratorUnitTest.java

Also, update SwiftShader. The bugs we encounter are known SwiftShader bugs that are unlikely to be fixed soon.

"Fix" image tests by extending blacklist

---

python/src/main/python/drivers/graphicsfuzz_piglit_converter.py

We don't need to error check the variable - json.load() just returns nothing if the JSON is empty, and errors out by itself if it detects malformed JSON.

Fix piglit converter not accepting blank JSON

---

common/src/main/java/com/graphicsfuzz/common/util/ShaderJobFileOperations.java
reducer/src/main/java/com/graphicsfuzz/reducer/tool/GlslReduce.java

A recent change removed the need to explicitly track whether
GraphicsFuzz defines are present in a shader, instead opting to emit
them if and only if the shader uses at least one GraphicsFuzz macro.
Some old code for tracking when the defines were used had been left
behind.  This change removes that old code.

Remove redundant code to check for GraphicsFuzz defines

---

ast/src/main/antlr4/com/graphicsfuzz/parser/GLSL.g4
ast/src/main/java/com/graphicsfuzz/common/ast/visitors/AstBuilder.java
ast/src/main/java/com/graphicsfuzz/common/ast/visitors/UnsupportedLanguageFeatureException.java
ast/src/test/java/com/graphicsfuzz/common/tool/PrettyPrinterVisitorTest.java
ast/src/test/java/com/graphicsfuzz/common/util/ParseHelperTest.java

The AstBuilder class, which turns an Antlr-parsed shader into a
GraphicsFuzz abstract syntax tree, was built on demand in the early
phases of the project and initially had many cases where runtime
exceptions would be thrown due to features being unsupported.
This change introduces a new runtime exception class,
UnsupportedLanguageFeatureException, to represent features that are
known to be unsupported at present (e.g. initializer lists), and
AstBuilder has been re-worked to throw
UnsupportedLanguageFeatureExceptions when feature support is lacking,
and plain RuntimeExceptions only for cases corresponding to an invalid
input shader.
In the process, the GLSL grammar file has been cleaned up a git - the
'?' operator is used to eliminate optional production rules in a
couple of places, some …

Rework AstBuilder to better track unsupported language features

---

reducer/src/main/java/com/graphicsfuzz/reducer/ReductionDriver.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/CompoundToBlockReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/GlobalVariableDeclToExprReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/IReductionOpportunityFinder.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/OutlinedStatementReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunitiesBase.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/RemoveRedundantUniformMetadataReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/SwitchToLoopReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/SwitchToLoopReductionOpportunity.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/VariableDeclToExprReductionOpportunities.java
reducer/src/test/java/com/graphicsfuzz/reducer/ReductionDriverTest.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/SwitchToLoopReductionOpportunitiesTest.java

Adds a reduction pass that will replace a switch statement with a loop
of the form:
do {
// Body of switch statement, minus 'case' and 'default' labels
} while (false);
The loop construct is convenient as it allows for 'break' statements.
Existing reduction passes will then try to remove the loop.
Does not apply when --preserve-semantics is used, unless the switch
statement is part of a dead code injection.
Fixes #610

Reduce switch statements by replacing switch with do..while(false)

---

generate-and-run-shaders/src/main/java/com/graphicsfuzz/generator/GenerateAndRunShaders.java
generate-and-run-shaders/src/test/java/com/graphicsfuzz/generator/GenerateAndRunShadersTest.java
generator/src/main/java/com/graphicsfuzz/generator/tool/Generate.java
generator/src/test/java/com/graphicsfuzz/generator/tool/GenerateTest.java

GlslGenerate and GenerateAndRunShaders both required a 'glsl-version'
argument that was subsequently never used, due to the shading language
version now being inferred from the shader itself.  This change
removes those arguments, and in passing cleans up various style issues
(such as using method references in favour of lambdas), and uses
ShaderJobFileOperations more consistently in some tests that were
affected by the change.
Fixes #619

Eliminate redundant GLSL version arguments

---

reducer/src/main/java/com/graphicsfuzz/reducer/ReductionDriver.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/IReductionOpportunityFinder.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunities.java

Related issue: #519 
The already implemented reducer that replaces the global variable declarations with the expression is not yet integrated into GraphicsFuzz. This PR adds the implementation for setting up such reducer with the reduction driver and reduction opportunities.

Add reducer opportunities

---

python/src/main/python/drivers/graphicsfuzz_piglit_converter.py
python/src/main/python/drivers/piglit-worker
python/src/main/python/drivers/piglit-worker.bat
python/src/main/python/drivers/piglit-worker.py

Fixes #582.
To run the worker, you need glxinfo and shader_runner_gles3 to be on your PATH - however, the script won't work until my corresponding PR to piglit for a -ignore-missing-uniforms argument is merged (should be soon).
The script is kind of a mess in terms of code quality right now, as my sole goal was 'get it working and usable' - code review is highly appreciated.

Add piglit shader_runner_gles3 worker script

---

python/src/main/python/drivers/graphicsfuzz_piglit_converter.py

graphicsfuzz-piglit-converter: support more uniform types

---

ast/src/main/java/com/graphicsfuzz/common/ast/stmt/BlockStmt.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/StmtReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/StmtReductionOpportunity.java
reducer/src/test/java/com/graphicsfuzz/reducer/ReductionDriverTest.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/StmtReductionOpportunitiesTest.java

The reducer needs to be a little conservative about removing non-void
return statements, to avoid making a shader invalid.  This change
makes the reducer less conservative by allowing it to remove a
statement that is or that contains a non-void return statement if
either:
- the enclosing function ends with a non-void return statement that is
not the statement being considered for removal, or
- the statement being considered for removal is in a block and is
preceded by a return statement in the block.
Some JavaDoc comments have been added along the way.
Fixes #493

Improve reducer's ability to remove return statements

---

reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/StmtReductionOpportunities.java

Two seemingly independent PRs had clashed: one improved encapsulation
of ScopeTrackingVisitor, the other depended on the existing less tight
encapsulation.  This change fixes the mismatch.

Fix compilation problems

---

python/src/main/python/drivers/runspv.py

Matrix uniforms were not currently supported in 'runspv', neither for
generation of AmberScript nor VkScript.  This change adds support in
the AmberScript case.

Add support for matrix uniforms in generation of AmberScript

---

generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateCodeTransformation.java
generator/src/main/java/com/graphicsfuzz/generator/util/GenerationParams.java
tester/src/test/java/com/graphicsfuzz/tester/GeneratorUnitTest.java

It is possible to get into a situation with live or dead code
injection where none of the available donors are compatible with the
reference.  For example, they might all share a named struct in common
(which at present is a source of incompatibility).  When such a
situation arises the generator would throw an exception.  This change
causes the generator, instead, to inject a null statement (;).
Fixes #645.

Gracefully handle scenario where no compatible donors are available

---

generator/src/main/java/com/graphicsfuzz/generator/knownvaluegeneration/ExpressionGenerator.java
util/src/main/java/com/graphicsfuzz/util/Constants.java

Fixes #652:
This PR adds a new implementation for generating a new method, `_GLF_init_globals`, that is in charge of initializing the global scope variables. 
```
void _GLF_init_globals();  // function prototype.
float foo;
void main() {
_GLF_init_globals(); // invokes a function to initialize global vars.
}
void _GLF_init_globals() { // function that assigns values for global vars.
foo = 1.0;
}
```

Expression Generator: Add global initializer method

---

shaders/src/main/glsl/samples/310es/binarysearch_tree_simple.frag
shaders/src/main/glsl/samples/310es/binarysearch_tree_simple.json

Adds a version of 'binarysearch_tree.frag' that is potentially less
floating point-sensitive, e.g. by not making use of trigonometric
functions nor functions such as 'fract'.

Add simpler version of binary search tree shader

---

generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateDeadCodeTransformation.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateLiveCodeTransformation.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/injection/BlockInjectionPoint.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/injection/IInjectionPoint.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/injection/IfInjectionPoint.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/injection/InjectionPoint.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/injection/InjectionPoints.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/injection/LoopInjectionPoint.java
generator/src/main/java/com/graphicsfuzz/generator/util/RemoveImmediateBreakStatements.java
generator/src/main/java/com/graphicsfuzz/generator/util/RemoveImmediateCaseLabels.java
generator/src/main/java/com/graphicsfuzz/generator/util/RemoveImmediateContinueStatements.java
generator/src/test/java/com/graphicsfuzz/generator/transformation/DonateDeadCodeTransformationTest.java
generator/src/test/java/com/graphicsfuzz/generator/transformation/DonateLiveCodeTransformationTest.java
generator/src/test/java/com/graphicsfuzz/generator/transformation/SplitForLoopTransformationTest.java
generator/src/test/java/com/graphicsfuzz/generator/transformation/injection/InjectionPointTest.java

Adds checks to make sure that we don't inject top-level 'case' or
'default' labels into code, by being aware of switch statements during
donation.  Does allow the insertion of top-level break statements into
switch statements (which was previously disallowed due to switch
statements not being considered, and loops being regarded as the only
acceptable place to add break statements).
Fixes #665.

Avoid injecting switch case labels into inappropriate places

---

shaders/src/main/glsl/samples/310es/bubblesort_flag.frag
shaders/src/main/glsl/samples/310es/bubblesort_flag_intfunctions.frag
shaders/src/main/glsl/samples/310es/bubblesort_flag_intfunctions.json
shaders/src/main/glsl/samples/310es/colorgrid_modulo_intfunctions.frag
shaders/src/main/glsl/samples/310es/colorgrid_modulo_intfunctions.json
shaders/src/main/glsl/samples/310es/mandelbrot_blurry_intfunctions.frag
shaders/src/main/glsl/samples/310es/mandelbrot_blurry_intfunctions.json
shaders/src/main/glsl/samples/310es/prefix_sum_intfunctions.frag
shaders/src/main/glsl/samples/310es/prefix_sum_intfunctions.json
shaders/src/main/glsl/samples/310es/squares_intfunctions.frag
shaders/src/main/glsl/samples/310es/squares_intfunctions.json

Implements #543. 
This PR adds modified versions of the default GraphicsFuzz shaders to the 310es directory that use GLES features not found in GLES 1.00, including do/while loops, while loops and Integer Functions.
Note - I couldn't make too many useful changes to colorgrid_modulo and squares - they heavily make use of floating point rather than integers and some parts of them rely on having a for loop(continue statement) rather than another type of control flow. Please make suggestions if you have any ideas for spicing those two up.

Add new versions of GraphicsFuzz shaders that use Integer Functions

---

gfauto/gfauto/tool.py
gfauto/temp/.gitignore

Don't require test metadata if you don't provide spirv_opt_args.
Also add temp directory that is ignored.

 gfauto: fix issue in tool

---

shaders/src/main/glsl/samples/310es/matrices_many_loops.frag
shaders/src/main/glsl/samples/310es/matrices_many_loops.json
shaders/src/main/glsl/samples/310es/matrices_smart_loops.frag
shaders/src/main/glsl/samples/310es/matrices_smart_loops.json

Adds two synthetic shaders that uses matrices to compute a greyscale
grid pattern.  Derived from more complex shaders that use matrix
uniforms but that cannot currently be handled by Amber due to the
following Amber issue:
https://github.com/google/amber/issues/616
The more complex shaders will eventually be added in addition, but
these simpler shaders allow better coverage of matrix types for now.

Add shaders that use all matrix types

---

gfauto/gfauto/amber_converter.py
gfauto/gfauto/android_device.py
gfauto/gfauto/host_device_util.py
gfauto/whitelist.dic

Modified amber generation script to add two pipelines and comparison of their framebuffers when reference shader job is present.

gfauto: generate amber code for comparing two shader jobs

---

ast/src/main/java/com/graphicsfuzz/common/typing/Typer.java
ast/src/test/java/com/graphicsfuzz/common/typing/TyperTest.java

These have been fixed to always return 'bool', even when comparing
vector types.  Tests for the vector relational builtins that allow
comparisons between vector types, to yield boolean vector results,
have been added.  Some incorrect tests have been removed.
Fixes #700.

Fix type checking of vector and relational operators

---

gfauto/gfauto/amber_converter.py
gfauto/gfauto/tool.py

Added support for converting a gfauto source directory containing wrong image case into an amber script which runs all the variants and compares the results against a reference.
Fixes #658

gfauto: Add support for generating multipipeline amber file from a source directory

---

generator/src/main/java/com/graphicsfuzz/generator/util/RemoveDiscardStatements.java
generator/src/main/java/com/graphicsfuzz/generator/util/RemoveImmediateBreakStatements.java
generator/src/main/java/com/graphicsfuzz/generator/util/RemoveImmediateCaseLabels.java
generator/src/main/java/com/graphicsfuzz/generator/util/RemoveImmediateContinueStatements.java
generator/src/main/java/com/graphicsfuzz/generator/util/RemoveReturnStatements.java
generator/src/main/java/com/graphicsfuzz/generator/util/RemoveStatements.java
generator/src/test/java/com/graphicsfuzz/generator/transformation/DonateLiveCodeTransformationTest.java
generator/src/test/java/com/graphicsfuzz/generator/transformation/injection/RemoveReturnStatementsTest.java

Before this change, the null statement, ';', was used when replacing
break, continue, case label and discard statements during live code
injection, and void return statements were completely removed.  The
latter - completely removing a return - caused problems when a return
appeared at the end of a switch statement.  Since it is questionable
whether it is OK for the final case/default label of a switch to be
followed by simply a null statement (e.g. glslangValidator gives a
warning about this), this change makes it so that the statement '1;'
is used in all cases where a null statement was previously used, and
is also used as a replacement for a void return.
Fixes #718.

Use '1;' instead of ';' when replacing jump statements

---

reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunitiesBase.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/CompoundExprToSubExprReductionOpportunitiesTest.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/ExprToConstantReductionOpportunitiesTest.java

The reducer could throw an exception due to trying to simplify case
statement labels, for which child querying and replacement is not
supported.  Rather than supporting child querying and replacement,
this change prevents the reducer from trying to simplify case labels.
Case labels already need to be literal expressions - so there is not
much to simplify - and changing the values of these literals would be
risky; for example it could easily lead to a switch statement with
duplicate case labels, which is not valid.
Fixes #697.

Prevent the reducer from trying to simplify case labels

---

CONTRIBUTORS

Added Abel Briggs and Jiradet Ounjai to the list of contributors in
recognition of their contributions to GraphicsFuzz via Google Summer
of Code.

Include GSoC students in list of contributors

---

gfauto/.gitignore
gfauto/gfauto/amber_converter.py

Added support for generating amber files from compute shader gfauto directiories that contain reference and multiple variants.

gfauto: Add multiple pipeline amber generation for compute

---

gfauto/Pipfile
gfauto/Pipfile.lock
gfauto/azure-pipelines.yml
gfauto/dev_shell.sh.template

Dependencies would possibly get updated if you changed `Pipfile`, but the intention was they should always get updated when executing `./dev_shell.sh.template`.
Now, dependencies never get updated unless you delete `Pipfile.lock`. Fixed an issue with dependency resolution by fixing `flake8-black` to version `==0.1.0`. Updated dependencies.

gfauto: fix dependency resolution and update dependencies

---

gfauto/gfauto/download_cts_gf_tests.py
gfauto/gfauto/run_cts_gf_tests.py
gfauto/gfauto/util.py

* Downloaded .amber tests have their shaders extracted, and now also are zipped for easier bug reporting. 
* Create work directory in run_cts_gf_tests.py. 
* Util function for creating zips

gfauto: improvements and fixes to *_cts_gf_tests

---

python/src/main/python/drivers/convert-shaders-to-spirv-fuzz-form.py
python/src/main/python/drivers/shader_job_uniforms_to_spirv_fuzz_facts.py

Minor edits to scripts that take a GraphicsFuzz shader and turn it
into a shader suitable for use with spirv-fuzz.

Fix scripts to make shaders spirv-fuzz-ready

---

shaders/src/main/glsl/samples/300es/binarysearch_tree.frag
shaders/src/main/glsl/samples/310es/binarysearch_tree.frag

The sinh() function caused the shader to be numerically unstable (differing result image with 3 and 64 bit floats). Since this was only used for making the output image look nice, replacing it with tan() still creates a relatively nice image while leaving the actual binary tree functionality alone.

Fix binarytree shader

---

gfauto/.idea/inspectionProfiles/profiles_settings.xml

PyCharm automatically deletes `USE_PROJECT_PROFILE` because its value is already the default

gfauto: fix .idea/inspectionProfiles/profiles_settings.xml

---

python/src/main/python/drivers/glsl-to-spv-worker.py
python/src/main/python/drivers/runspv.py
python/src/main/python/test_scripts/test_runspv/runspv_tests.py

AmberScript support is now working well, so we no longer need VkScript
support to cross-check against.
Fixes #751.

Remove VkScript support from runspv

---

shaders/src/main/glsl/samples/300es/quicksort_palette.frag
shaders/src/main/glsl/samples/310es/quicksort_palette.frag

Multiplying floating point 1.0 with a large number followed by fract() may not result in expected result. Adding a fudge factor before fract stabilizes this, making 64bit and 32bit float return the same result even when asking more results than the default grid in the shader does. With the default grid, I could mask out 3 of the bits from the 32bit float before I got a different result compared to 64bit floats.

Added fudge factor to calculation to make it more stable

---

shaders/src/main/glsl/samples/300es/mergesort_mosaic.frag
shaders/src/main/glsl/samples/310es/mergesort_mosaic.frag

acosh() is only defined for input values >=1, but the shader feeds values that are less than that (including negative values). This leads to undefined behavior as per SPIR-V spec. In C++ the result may have bee NaN, which is optional in Vulkan.

Fix acosh() input range

---

shaders/src/main/glsl/samples/310es/muller.frag
shaders/src/main/glsl/samples/310es/muller.json

Related issue: #545 
**muller**
- Given a uniform vec3 `polynomial` representing the constants of a quadratic function, and a uniform vec3 `initial_xvalues` that represents the xvalues to begin the algorithm with (with `initial_xvalues.y` being the midpoint of `[initial_xvalues.x, initialxvalues.z]`), approximates a root of `polynomial` nearest to `initial_xvalues` by approximating using quadratic functions.
- Uses a while loop
- Math-heavy
- Renders red if the test passes (the method finds the correct root, given a small margin of error), otherwise green
From some fuzz testing, this shouldn't be vulnerable to floating point issues and should give consistent results.

New 310es shader - Muller's method

---

gfauto/gfauto/amber_converter.py

If a shader has no uniforms, this change avoids generating "uniforms
for ..." followed by no uniform information.  This was motivated by
such redundant text in Amber files being flagged up in Vulkan CTS
reviews.

gfauto: do not generate Amber text for uniforms if there are none

---

reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/FlattenControlFlowReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/InlineInitializerReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunitiesBase.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/SimplifyExprReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/StmtReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/VariableDeclReductionOpportunities.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/InlineInitializerReductionOpportunitiesTest.java

The reducer tries to be clever and do some initializer inlining when
preserving semantics.  But this can be problematic for a couple of
reasons:
- It can make references and variants hard to compare if initializer
inlining has been applied to one and not the other
- There are subtle cases where initializer inlining does not preserve
semantics; for example:
highp int x = 16777216;
findLSB(x);
might not be equivalent to:
findLSB(16777216);
since findLSB can operate at low precision when passed a literal
argument.
This change disables initializer inlining when semantics are being
preserved, unless the initializer occurs in dead code, or is the
initializer for a live-injected variable.
The change contributes some clean-up related to how dead code and
live-injected variables are identified in …

Restrict initializer inlining when preserving semantics

---

gfauto/gfauto/add_amber_tests_to_cts.py

add_amber_test_to_cts.py used amber file names (including .amber suffix)
to order the lines in the cpp file and test names to order the lines in the must pass lists.
This may lead to inconsistent order in cpp and must pass lists in some rare cases.
For example the following test would be ordered in the wrong way if the amber file names are used:
unreachable-discard-statement-in-if.amber
unreachable-discard-statement.amber
This commit changes the cpp file generator to order the lines by test name.

Fix cts test list generator ordering logic

---

reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/InlineUniformReductionOpportunities.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/InlineUniformReductionOpportunitiesTest.java

In order to make reference and variant shaders easier to compare, this
stops the reducer from inlining uniforms when preserving semantics,
unless the uniforms are live-injected, or the use being inlined is in
dead code.
Partly fixes #783.
Fixes #639.

Reducer: inline uniforms less when preserving semantics

---

reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/FoldConstantReductionOpportunities.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/FoldConstantReductionOpportunitiesTest.java

To make references and reduced variants easier to compare, this change
supresses constant folding in non-injected code when semantics are
being preserved.

Reducer: limit constant folding when preserving semantics

---

gfauto/gfauto/android_device.py
gfauto/gfauto/binaries_util.py
gfauto/gfauto/devices_util.py
gfauto/whitelist.dic

We previously used the "amber_ndk" binary that could be pushed to a phone and executed via `adb shell ./amber_ndk`. Although this is convenient, it is not clearly supported. We now install the new Amber APK and Amber test APK, and use `adb shell am instrument ...` to run Amber. Files are now written to `/sdcard/Android/data/com.google.amber/cache/graphicsfuzz` instead of `/data/local/tmp/graphicsfuzz`.

gfauto: use Amber apk

---

gfauto/gfauto/fuzz_glsl_test.py
gfauto/gfauto/fuzz_spirv_test.py
gfauto/gfauto/glslang_validator_util.py
gfauto/gfauto/spirv_opt_util.py
gfauto/gfauto/tool.py
gfauto/gfauto/util.py
gfauto/whitelist.dic

We run glslangValidator and spirv-opt multiple times on the same files redundantly when testing multiple devices (in particular, host_preprocessor followed by a real device). This change adds a cache to avoid this expensive re-running.

gfauto: cache runs of glslangValidator and spirv-opt

---

gfauto/gfauto/fuzz.py
gfauto/gfauto/fuzz_glsl_test.py
gfauto/gfauto/fuzz_spirv_test.py
gfauto/gfauto/interrupt_util.py
gfauto/whitelist.dic

When running many instances of gfauto, it can be useful to trigger termination of the instances, but allow the final steps (including reduction) of processing a report to complete. This change overrides sigint to allow for termination at "safe points". A second sigint is not ignored.

gfauto: catch sigint to allow graceful exit

---

ast/src/main/java/com/graphicsfuzz/common/typing/Typer.java

This change teaches the typechecker what type to give expressions that
are invocations of GraphicsFuzz macros, such as _GLF_DEAD and
_GLF_IDENTITY.

Teach typechecker about GraphicsFuzz macros

---

gfauto/gfauto/fuzz_glsl_test.py
gfauto/gfautotests/test_large.py

When fuzzing, don't create a report (i.e. discard the test) if the crash signature is in ignored_crash_signatures for the device. Also fix minor issue revealed by test -- don't create the crash signature directory until needed; this way we can check that the directory was NOT created as part of the test.

gfauto: skip ignored_crash_signatures

---

gfauto/gfauto/devices_util.py

There is no need to download this when generating the settings.json file; we only need the Binary data structure, not the actual binary path (which requires downloading and extracting).

gfauto: don't download amdllpc by default

---

gfauto/gfauto/devices_util.py
gfauto/gfauto/fuzz.py

Adds an active device name, overriding those in the settings.json file. This allows sharing one settings.json file between multiple instances of gfauto_fuzz.

gfauto: add active_device cl flag

---

gfauto/gfauto/fuzz.py
gfauto/gfautotests/test_fuzz.py

Add --spirv_fuzz_iterations S and --glsl_fuzz_iterations G for specifying the number of times to run each tool. E.g. G=2,S=1 will run glsl-fuzz twice, then spirv-fuzz once, then repeat. The default is just glsl-fuzz.

gfauto: alternating glsl- and spirv-fuzz

---

gfauto/gfauto/signature_util.py
gfauto/gfautotests/test_signature_util.py

Improve Android crash signatures for library/driver inside an APK. E.g. prerelease driver. Add test.

gfauto: improve get_signature

---

gfauto/gfauto/signature_util.py

Make the "ERROR: blah" pattern case insensitive, which should help catch NIR error messages.

gfauto: improve "error:" crash signature

---

gfauto/gfauto/spirv_opt_util.py

This list can be used later when running spirv-opt on our CTS tests, along with -O and -Os.

gfauto: interesting subset of spirv-opt passes

---

common/src/main/java/com/graphicsfuzz/common/util/GloballyTruncateLoops.java
common/src/main/java/com/graphicsfuzz/common/util/MakeArrayAccessesInBounds.java
common/src/test/java/com/graphicsfuzz/common/util/GloballyTruncateLoopsTest.java
common/src/test/java/com/graphicsfuzz/common/util/MakeArrayAccessesInBoundsTest.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateCodeTransformation.java
reducer/src/main/java/com/graphicsfuzz/reducer/ReductionDriver.java
util/src/main/java/com/graphicsfuzz/util/Constants.java

This change leverages two existing pieces of functionality, for adding
global loop limiting to a shader, and making array accesses in-bounds,
to make a semantics-changing reduction less prone to undefined
behaviour due to long-running loops or out-of-bounds
array/vector/matrix accesses.

Guard against undefined behaviour in the reducer

---

ast/src/main/java/com/graphicsfuzz/common/ast/type/ArrayType.java
ast/src/main/java/com/graphicsfuzz/common/ast/type/AtomicIntType.java
ast/src/main/java/com/graphicsfuzz/common/ast/type/BasicType.java
ast/src/main/java/com/graphicsfuzz/common/ast/type/ImageType.java
ast/src/main/java/com/graphicsfuzz/common/ast/type/QualifiedType.java
ast/src/main/java/com/graphicsfuzz/common/ast/type/SamplerType.java
ast/src/main/java/com/graphicsfuzz/common/ast/type/StructDefinitionType.java
ast/src/main/java/com/graphicsfuzz/common/ast/type/StructNameType.java
ast/src/main/java/com/graphicsfuzz/common/ast/type/Type.java
ast/src/main/java/com/graphicsfuzz/common/ast/type/VoidType.java
ast/src/test/java/com/graphicsfuzz/common/ast/type/StructDefinitionTypeTest.java
common/src/main/java/com/graphicsfuzz/common/util/AddInitializers.java
common/src/main/java/com/graphicsfuzz/common/util/ShaderJobFileOperations.java
common/src/test/java/com/graphicsfuzz/common/util/AddInitializersTest.java
generator/src/main/java/com/graphicsfuzz/generator/semanticspreserving/AddJumpMutation.java

Adds a utility for adding initializers to all variables in a shader
job, and in the process adds support for generation of canonical
constants for arrays and structs.  The latter requires passing a scope
around during canonical constant generation, to look up the
definitions of named structs.

Array/struct canonical constants + variable initialization utility

---

reducer/src/main/java/com/graphicsfuzz/reducer/ReductionDriver.java
reducer/src/test/java/com/graphicsfuzz/reducer/ReductionDriverTest.java

This gives the reducer the option, when semantics are not being
preserved, to initialize every variable in the shader during
reduction, to try to avoid uninitialized reads in reduced shaders.

Integrate variable initializers in reducer

---

reducer/src/main/java/com/graphicsfuzz/reducer/CheckAstFeatureVisitor.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ExprToConstantReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunitiesBase.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/SimplifyExprReductionOpportunities.java
reducer/src/test/java/com/graphicsfuzz/reducer/ReductionDriverTest.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/ExprToConstantReductionOpportunitiesTest.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunitiesTest.java

Before this change, the reducer would not attempt to simplify
literals, so that e.g. 8092.6 would remain in a reduced shader, even
if in dead code. This was based on the assumption that the exact form
of final literals would not really be important. However, having
worked a lot with the reducer it is certainly the case that a final
shader that does not involve weird literal values is easier to
understand than one that does. This change allows the reducer to
simplify any literal that is not in canonical form to one that is.
We should keep an eye on the knock-on effect this has on reducer
performance; by creating more reduction opportunities we could see a
performance drop.

Simplify literals more aggressively in the reducer

---

docs/finding-a-vulkan-driver-bug-using-spirv-fuzz.md

...so that the binder link uses a specific commit hash.

Pin finding-a-vulkan-driver-bug-using-spirv-fuzz.md

---

ast/src/main/java/com/graphicsfuzz/common/util/MacroNames.java
reducer/src/test/java/com/graphicsfuzz/reducer/ReductionDriverTest.java

When deciding whether to emit GraphicsFuzz macros, the presence of
macros to clamp arrays into bounds was not being checked.  This change
fixes this.

Detect array bounds clamping macros

---

ast/src/main/java/com/graphicsfuzz/common/glslversion/CompositeShadingLanguageVersion.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl100.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl300.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl110.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl120.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/ShadingLanguageVersion.java
generator/src/main/java/com/graphicsfuzz/generator/fuzzer/Fuzzer.java

Fixes an issue where shading language support for array constructors
was incorrect, which was leading to array constructors not being
generated.

Get array constructor support right in shading languages

---

ast/src/main/java/com/graphicsfuzz/common/ast/type/ArrayType.java
ast/src/main/java/com/graphicsfuzz/common/ast/visitors/AstBuilder.java
ast/src/main/java/com/graphicsfuzz/common/typing/ScopeTrackingVisitor.java
ast/src/test/java/com/graphicsfuzz/common/tool/PrettyPrinterVisitorTest.java
ast/src/test/java/com/graphicsfuzz/common/typing/TyperTest.java
generator/src/main/java/com/graphicsfuzz/generator/fuzzer/Fuzzer.java
generator/src/main/java/com/graphicsfuzz/generator/semanticschanging/Expr2ArrayAccessMutationFinder.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateCodeTransformation.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateDeadCodeTransformation.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateLiveCodeTransformation.java
util/src/main/java/com/graphicsfuzz/util/Constants.java

This change does two things:
(1) It corrects the way that qualifiers (in particular const) are
interpreted when applied to array types.  A declaration:
const int v[2] = ...;
should be regarded as having type:
QualifiedType(ArrayType(int, 2), CONST)
but was being regarded as having type:
ArrayType(QualifiedType(int, CONST), 2)
(2) It changes the way array constructor expressions are fuzzed.
Previously, an array constructor for an array of size 256 was fuzzed
by trying to make 256 distinct expressions.  The chances of the fuzzer
getting stuck and generating a "fuzzed into a corner" exception were
very high in such cases.  This change uses an approach with a much
lower probability of failure, whereby a number of element constructor
expressions are generated and then re-used several times at …

Const arrays, and fuzzing of array constructors

---

gfauto/gfauto/fuzz_glsl_test.py
gfauto/gfauto/util.py
gfauto/pylintrc

Bug report directories were being generated from reduced_stage_one_result due to a copy-paste mistake. Also, create a zip archive of the bug_report dir for convenience.

gfauto: fix bug report

---

gfauto/gfauto/run_bin.py

Document that you need to use -- to separate args. If a settings.json file gets generated, catch the exception and try again instead of failing.

gfauto: improve run_bin

---

gfauto/.idea/inspectionProfiles/profiles_settings.xml
gfauto/gfauto/fuzz_spirv_test.py
gfauto/gfauto/spirv_fuzz_util.py
gfauto/whitelist.dic

gfauto will now populate, per test, a list of donor shaders based on
the corpus of SPIR-V shaders provided.

Add support for spirv-fuzz donors to gfauto

---

ast/src/main/java/com/graphicsfuzz/common/ast/decl/ArrayInfo.java
ast/src/main/java/com/graphicsfuzz/common/ast/decl/ParameterDecl.java
ast/src/main/java/com/graphicsfuzz/common/ast/inliner/Inliner.java
ast/src/main/java/com/graphicsfuzz/common/ast/type/ArrayType.java
ast/src/main/java/com/graphicsfuzz/common/ast/visitors/AstBuilder.java
ast/src/main/java/com/graphicsfuzz/common/ast/visitors/StandardVisitor.java
ast/src/main/java/com/graphicsfuzz/common/tool/PrettyPrinterVisitor.java
ast/src/main/java/com/graphicsfuzz/common/typing/ScopeTrackingVisitor.java
ast/src/main/java/com/graphicsfuzz/common/typing/Typer.java
ast/src/test/java/com/graphicsfuzz/common/ast/type/ArrayTypeTest.java
ast/src/test/java/com/graphicsfuzz/common/tool/PrettyPrinterVisitorTest.java
ast/src/test/java/com/graphicsfuzz/common/typing/TyperTest.java
common/src/main/java/com/graphicsfuzz/common/util/UpgradeShadingLanguageVersion.java
common/src/test/java/com/graphicsfuzz/common/util/MakeArrayAccessesInBoundsTest.java

This change applies constant folding to the sizes of array parameters
during AST construction, refines equality on array types to regard
array types as equal if and only if their base types are equal and
they agree on constant sizes, and adapts the logic to check whether
arguments match a function prototype to allow array types.
Fixes #784.

Support array parameters

---

ast/src/main/java/com/graphicsfuzz/common/ast/type/ArrayType.java
ast/src/main/java/com/graphicsfuzz/common/ast/type/AtomicIntType.java
ast/src/main/java/com/graphicsfuzz/common/ast/type/BasicType.java
ast/src/main/java/com/graphicsfuzz/common/ast/type/ImageType.java
ast/src/main/java/com/graphicsfuzz/common/ast/type/QualifiedType.java
ast/src/main/java/com/graphicsfuzz/common/ast/type/SamplerType.java
ast/src/main/java/com/graphicsfuzz/common/ast/type/StructDefinitionType.java
ast/src/main/java/com/graphicsfuzz/common/ast/type/StructNameType.java
ast/src/main/java/com/graphicsfuzz/common/ast/type/Type.java
ast/src/main/java/com/graphicsfuzz/common/ast/type/VoidType.java
ast/src/main/java/com/graphicsfuzz/common/typing/Scope.java
ast/src/main/java/com/graphicsfuzz/common/typing/ScopeTrackingVisitor.java
ast/src/test/java/com/graphicsfuzz/common/ast/type/BasicTypeTest.java
ast/src/test/java/com/graphicsfuzz/common/ast/type/StructDefinitionTypeTest.java
ast/src/test/java/com/graphicsfuzz/common/ast/type/VoidTypeTest.java
common/src/main/java/com/graphicsfuzz/common/util/AddInitializers.java
generator/src/main/java/com/graphicsfuzz/generator/fuzzer/FuzzingContext.java
generator/src/main/java/com/graphicsfuzz/generator/semanticspreserving/AddJumpMutation.java
generator/src/main/java/com/graphicsfuzz/generator/semanticspreserving/StructificationMutation.java
generator/src/main/java/com/graphicsfuzz/generator/util/FreeVariablesCollector.java
generator/src/main/java/com/graphicsfuzz/generator/util/RestrictFragmentShaderColors.java
generator/src/test/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGeneratorTest.java
generator/src/test/java/com/graphicsfuzz/generator/semanticspreserving/OutlineStatementMutationTest.java
generator/src/test/java/com/graphicsfuzz/generator/transformation/injection/InjectionPointTest.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ExprToConstantReductionOpportunities.java

This change makes the 'scope' parameters of hasCanonicalConstant and
getCanonicalConstant (on Type) compulsory.  An empty scope can be
passed in cases where it would be difficult to get access to a scope
and where it is known that struct name types will not be encountered.
This was motivated by a bug where a scope had been passed in the 'has'
call but not the 'get' call, which this change also fixes.
In the process the change overloads the Scope constructor so that a
global scope (with a null parent) is made from a zero-argument
constructor, rather than by passing in a null parent.  A few other
cleanups suggested by IntelliJ are also applied.

Make scopes compulsory when looking for canonical constants

---

ast/src/main/java/com/graphicsfuzz/common/glslversion/CompositeShadingLanguageVersion.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl100.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl310.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl110.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl430.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/ShadingLanguageVersion.java
ast/src/main/java/com/graphicsfuzz/common/typing/TyperHelper.java

This change provides the typechecker with knowledge of the atomic
memory functions that are available to compute shaders.

Teach the typechecker about atomic memory functions

---

ast/src/main/java/com/graphicsfuzz/common/ast/decl/InterfaceBlock.java
ast/src/main/java/com/graphicsfuzz/common/ast/visitors/AstBuilder.java
ast/src/main/java/com/graphicsfuzz/common/tool/PrettyPrinterVisitor.java
ast/src/main/java/com/graphicsfuzz/common/typing/Typer.java
ast/src/test/java/com/graphicsfuzz/common/typing/TyperTest.java
ast/src/test/java/com/graphicsfuzz/common/util/ParseHelperTest.java

This change formalizes a previously implicit assumption that interface
blocks are not named, adds type-checking for members of interface
blocks, and considers array members of interface blocks when resolving
array sizes.

Type-checking for interface blocks

---

generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateCodeTransformation.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateLiveCodeTransformation.java
generator/src/test/java/com/graphicsfuzz/generator/tool/GenerateShaderFamilyTest.java
generator/src/test/java/com/graphicsfuzz/generator/transformation/donation/CheckDonorVersionMatchesTest.java
tester/src/test/java/com/graphicsfuzz/tester/GeneratorUnitTest.java
util/src/main/java/com/graphicsfuzz/util/Constants.java

Before this change, only .frag shaders were being used as donors, and
they were being used as donors for .vert and .comp shaders.
This change forces the generator to consider only shaders of the same
kind as the reference for donation into the reference.
Because this allows .comp shaders to be donated into .comp shaders,
which was not happening before, it exposed some limitations relating
to compute shader donation, specifically that the various compute
shader builtin variables were not being handled correctly, and that
interface blocks were not being handled in donation.  A similar issue,
with builtin variables, applied to vertex shaders.
This change introduces solutions to those problems.

Only use donors of the same shader kind as the reference

---

ast/src/main/java/com/graphicsfuzz/common/ast/visitors/AstBuilder.java
ast/src/test/java/com/graphicsfuzz/common/tool/PrettyPrinterVisitorTest.java

Some shaders in the wild use (void) to indicate no arguments to a
function; this change handles this by turning such declarations into
zero-argument functions when building the AST.

Account for void parameters

---

generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateDeadCodeTransformation.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateLiveCodeTransformation.java
generator/src/test/java/com/graphicsfuzz/generator/transformation/DonateDeadCodeTransformationTest.java
generator/src/test/java/com/graphicsfuzz/generator/transformation/DonateLiveCodeTransformationTest.java

When generating a local variable for a free variable appearing in a
piece of generated code, we need to strip the variable's type of
qualifiers that don't make sense on local variables (such as 'in',
'out' and 'inout').  A previous change had messed this up.  This adds
tests to expose the problem and fixes the problem.

Fix to local variable generation during donation

---

ast/src/main/java/com/graphicsfuzz/common/glslversion/CompositeShadingLanguageVersion.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl100.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl300.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Essl310.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl110.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl130.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/Glsl400.java
ast/src/main/java/com/graphicsfuzz/common/glslversion/ShadingLanguageVersion.java
ast/src/main/java/com/graphicsfuzz/common/typing/TyperHelper.java
ast/src/test/java/com/graphicsfuzz/common/typing/TyperTest.java
generator/src/main/java/com/graphicsfuzz/generator/fuzzer/Fuzzer.java

This change adds knowledge to the typechecker about various functions
for reading from textures, and various builtins available to compute
shaders.

Add support for some texture and compute builtins

---

generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
generator/src/main/java/com/graphicsfuzz/generator/semanticspreserving/IdentityMutationFinder.java
generator/src/main/java/com/graphicsfuzz/generator/tool/GeneratorArguments.java
generator/src/test/java/com/graphicsfuzz/generator/semanticspreserving/IdentityMutationFinderTest.java

Fixes an issue where identity mutations were wrongly being applied to constant expressions, leading to invalid code.

Do not apply identity mutations to constant expressions

---

ast/src/main/java/com/graphicsfuzz/common/typing/ScopeTrackingVisitor.java
generator/src/main/java/com/graphicsfuzz/generator/semanticspreserving/VectorizeMutationFinder.java
generator/src/test/java/com/graphicsfuzz/generator/semanticspreserving/VectorizeMutationFinderTest.java

Fixes a problem where the tracking of scopes by the vectorizer was not working properly for single-statement for (and while) loops, which introduce new scopes even though they do not have blocks as bodies.

Fixed bug in vectorizer related to single statement for loops.

---

ast/src/main/java/com/graphicsfuzz/common/ast/expr/FunctionCallExpr.java
ast/src/main/java/com/graphicsfuzz/common/ast/expr/TypeConstructorExpr.java
generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java
generator/src/test/java/com/graphicsfuzz/generator/semanticspreserving/IdentityMutationFinderTest.java

This PR adds parentheses as needed to comma expressions when they
become arguments to macros or functions, e.g. when the 'e -> min(e,
e)' transformation is applied to the comma expression 'a, b', we want
to end up with 'min((a, b), (a, b))', not 'min(a, b, a, b)'.

Add parentheses when identities are applied to comma expressions

---

common/src/main/java/com/graphicsfuzz/common/transformreduce/GlslShaderJob.java
common/src/test/java/com/graphicsfuzz/common/transformreduce/GlslShaderJobTest.java

Some shaders in the wild declare several uniforms in a single
variables declaration statement, which was not supported when adding
uniform bindings; this PR adds support.

Support multiple uniforms per variables declaration

---

ast/src/main/java/com/graphicsfuzz/common/typing/Typer.java
ast/src/main/java/com/graphicsfuzz/common/util/OpenGlConstants.java
ast/src/test/java/com/graphicsfuzz/common/typing/TyperTest.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateCodeTransformation.java

This teaches the typechecker about gl_PointCoord, and also puts
gl_PointSize in scope during code donation (an omission from when
support for gl_PointSize is added).

Typecheck gl_PointCoord

---

generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateCodeTransformation.java
generator/src/test/java/com/graphicsfuzz/generator/transformation/DonateLiveCodeTransformationTest.java

Fixes an issue where the matnxn type constructors were not being
recognized as basic type constructors during donation, and were thus
being given a prefix.

Handle square matrix type constructors properly in donation

---

generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java

Fixes an issue where an identity function that uses the 'mix' builtin
could create a type constructor expression with a comma expression as
a top-level argument.

Avoid use of comma operator as type constructor parameter

---

generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateCodeTransformation.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/donation/DonationContextFinder.java
generator/src/test/java/com/graphicsfuzz/generator/transformation/DonateLiveCodeTransformationTest.java

Local structs are complex when performing code donation.  For
simplicity, this change means that functions that introduce local
structs are not considered when choosing fragments of code to donate.

Do not allow local structs during donation

---

ast/src/main/java/com/graphicsfuzz/common/ast/ParentMap.java
ast/src/main/java/com/graphicsfuzz/common/ast/decl/ArrayInfo.java
ast/src/main/java/com/graphicsfuzz/common/ast/visitors/StandardVisitor.java
ast/src/test/java/com/graphicsfuzz/common/ast/decl/ArrayInfoTest.java
common/src/test/java/com/graphicsfuzz/common/util/StripUnusedGlobalsTest.java
generator/src/main/java/com/graphicsfuzz/generator/mutateapi/MutationFinderBase.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateCodeTransformation.java
generator/src/main/java/com/graphicsfuzz/generator/util/FreeVariablesCollector.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunitiesBase.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/SimplifyExprReductionOpportunities.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/VariableDeclReductionOpportunitiesTest.java

We recently added the notion of a size expression to an ArrayInfo
node.  This change enhances StandardVisitor to visit size expressions,
so that they are considered when walking the AST.  Sometimes we don't
want them to be visited, so some visitors have been adapted to
override this method in order to block it.  We also now want to avoid
any sharing of ArrayInfo nodes in the AST, so the change removes its
equals and hashCode methods and adds clonability.

Visit size expressions of ArrayInfo nodes

---

ast/src/main/java/com/graphicsfuzz/common/ast/expr/ArrayIndexExpr.java
ast/src/main/java/com/graphicsfuzz/common/ast/expr/BinaryExpr.java
ast/src/main/java/com/graphicsfuzz/common/ast/expr/Expr.java
ast/src/main/java/com/graphicsfuzz/common/ast/expr/FunctionCallExpr.java
ast/src/main/java/com/graphicsfuzz/common/ast/expr/MemberLookupExpr.java
ast/src/main/java/com/graphicsfuzz/common/ast/expr/TernaryExpr.java
ast/src/main/java/com/graphicsfuzz/common/ast/expr/TypeConstructorExpr.java
ast/src/main/java/com/graphicsfuzz/common/ast/expr/UnaryExpr.java
ast/src/main/java/com/graphicsfuzz/common/ast/visitors/AstBuilder.java
ast/src/test/java/com/graphicsfuzz/common/util/ParseHelperTest.java
generator/src/main/java/com/graphicsfuzz/generator/fuzzer/OpaqueExpressionGenerator.java

The comma operator should never occur as the top-level argument to an
expression such as a binary or unary expression, with few exceptions
(e.g. a parentheses expression).  This change introduces checks to
guard against this, and to make it clear that using a comma in the
'then' expression of a ternary is not supported (even though it is
allowed in GLSL).

Guard against occurrences of comma in most expressions

---

common/src/main/java/com/graphicsfuzz/common/util/PruneUniforms.java
common/src/test/java/com/graphicsfuzz/common/util/PruneUniformsTest.java

Bool uniforms are represented as integers at the API level, and were
being inlined into shaders as integer literals.  This change addresses
this, so that they are inlined as bool literals.

Use proper literal names when inlining bool uniforms

---

generator/src/main/java/com/graphicsfuzz/generator/semanticspreserving/OutlineStatementMutationFinder.java
generator/src/test/java/com/graphicsfuzz/generator/semanticspreserving/OutlineStatementMutationFinderTest.java

Fixes an issue where the function outliner would end up with a stale
scope, and give the outlined function the wrong return type.

Fix to function outliner

---

shaders/src/main/glsl/samples/310es/stable_bifurcation.frag
shaders/src/main/glsl/samples/310es/stable_binarysearch_tree.frag
shaders/src/main/glsl/samples/310es/stable_bubblesort_flag.frag
shaders/src/main/glsl/samples/310es/stable_collatz.frag
shaders/src/main/glsl/samples/310es/stable_colorgrid_modulo.frag
shaders/src/main/glsl/samples/310es/stable_maze.frag
shaders/src/main/glsl/samples/310es/stable_mergesort.frag
shaders/src/main/glsl/samples/310es/stable_orbit.frag
shaders/src/main/glsl/samples/310es/stable_pillars.frag
shaders/src/main/glsl/samples/310es/stable_quicksort.frag
shaders/src/main/glsl/samples/310es/stable_rects.frag
shaders/src/main/glsl/samples/310es/stable_triangle.frag

Added line `precision highp int` to all shaders in `graphicsfuzz/shaders/src/main/glsl/samples/310es` that have a `stable_` prefix in the name. This way all drivers must use the same level of precision.

Add line "precision highp int" to stable shaders

---

ast/src/main/java/com/graphicsfuzz/common/ast/expr/TernaryExpr.java
ast/src/main/java/com/graphicsfuzz/common/ast/visitors/AstBuilder.java
ast/src/test/java/com/graphicsfuzz/common/util/ParseHelperTest.java

This change adds test to check that ternary expressions that use the
comma operator are correctly parsed, and removes a defensive check
that previously disallowed the use of comma in the 'then' expression
of a ternary.  This means that the idiom 'a ? b, c : d' is now
supported.

Allow comma as 'then' expression in ternary

---

ast/src/main/java/com/graphicsfuzz/common/ast/visitors/AstBuilder.java
ast/src/main/java/com/graphicsfuzz/common/typing/Typer.java
ast/src/main/java/com/graphicsfuzz/common/typing/TyperHelper.java
ast/src/test/java/com/graphicsfuzz/common/typing/TyperTest.java

The GraphicsFuzz typechecker was originally "best effort", and
tolerated null entries for expressions that could not yet be typed.
This change tightens up the typechecker so that null types are not
tolerated.

Make typechecker strict

---

generator/src/main/java/com/graphicsfuzz/generator/semanticspreserving/OutlineStatementMutation.java
generator/src/test/java/com/graphicsfuzz/generator/semanticspreserving/OutlineStatementMutationFinderTest.java

Fixes an issue where a struct definition could be duplicated by the
statement outliner, if a variable used in the statement being outlined
had a named struct definition as its type.

Do not duplicate structs when outlining statements

---

ast/src/main/java/com/graphicsfuzz/common/typing/Typer.java
ast/src/main/java/com/graphicsfuzz/common/typing/TyperHelper.java
ast/src/test/java/com/graphicsfuzz/common/typing/TyperTest.java

Fixes an issue where a function call expression would not be typed if
an expression of struct definition type was passed where an expression
of the associated struct name type was required.

Improve function prototype matching to account for struct types

---

common/src/main/java/com/graphicsfuzz/common/util/PruneUniforms.java
common/src/test/java/com/graphicsfuzz/common/util/PruneUniformsTest.java
generator/src/main/java/com/graphicsfuzz/generator/tool/Generate.java
generator/src/main/java/com/graphicsfuzz/generator/tool/KnownValueShaderGenerator.java
generator/src/main/java/com/graphicsfuzz/generator/tool/PrepareReference.java

Instead of throwing an exception if a reference shader has too many
uniforms, or if it is not possible to bring the number of uniforms in
a variant shader down to size by pruning injected uniforms, this
change makes uniform pruning more liberal so that shaders are always
pruned down to size by pruning original uniforms if needed.

Be more liberal with uniform pruning

---

generator/src/main/java/com/graphicsfuzz/generator/fuzzer/Fuzzer.java
generator/src/main/java/com/graphicsfuzz/generator/semanticspreserving/AddSwitchMutation.java
generator/src/main/java/com/graphicsfuzz/generator/util/GenerationParams.java
generator/src/test/java/com/graphicsfuzz/generator/semanticspreserving/AddSwitchMutationFinderTest.java

When injecting switch statements, care was not being taken to account
for variables declared in the original code being added to the scope
used for fuzzing unreachable switch cases that occur after the
reachable code.  This change fixes said problem, including some
reworking of generation parameters that made the fix easier to test.

Fix name shadowing problem with switch statements

---

gfauto/gfauto/fuzz.py

When using --active_device, the ignored crashes for host_preprocessor were not being used. Now they are.

gfauto: fix ignored crashes

---

gfauto/gfauto/android_device.py
gfauto/whitelist.dic

`adb logcat -c` does not always seem to clear the log of an Android device. This can cause old log events to be interpreted as recent errors, causing reduction steps to incorrectly fail. Thus, we now attempt to clear the log (as before) and then make a note of the last visible timestamp. This timestamp is then used to ignore old log events when we next capture the log.

gfauto: fix logcat clearing

---

gfauto/gfauto/signature_util.py

Increase the priority of the bad image signature. Make the "amber error" signature more specific to avoid incorrectly classifying logcat noise as the signature.

gfauto: fix signature priority and false-positive

---

gfauto/gfauto/add_amber_tests_to_cts.py

In add_amber_tests_to_cts.py, update the indices in a test description line so we can have longer test names.

gfauto: allow longer CTS test names

---

ast/src/main/java/com/graphicsfuzz/common/util/TruncateLoops.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/FlattenControlFlowReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/StmtReductionOpportunities.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunitiesTest.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/StmtReductionOpportunitiesTest.java
util/src/main/java/com/graphicsfuzz/util/Constants.java

The statement removal reduction pass is enhanced with an analysis that
figures out those loops whose removal will not affect the limiting
(via loop limiters) of other loops.  This is used when looking for
statements to remove: a live-injected loop whose removal is known not
to impact the limiting of other loops can be removed.

Smarter removal of loops with limiters

---

reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/StmtReductionOpportunities.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunitiesTest.java

This change teaches the reducer how to remove a statement of the form:
live_injected_variable[...] = ...

Allow removal of live-injected array assignments

---

gfauto/gfauto/download_cts_gf_tests.py
gfauto/gfauto/fuzz.py
gfauto/gfauto/run_cts_gf_tests.py
gfauto/whitelist.dic

Add --update_ignored_crash_signatures to the gfauto_fuzz command. This downloads and runs GraphicsFuzz AmberScript tests to update known crash signatures for every active device. You could already do this by running download_cts_gf_tests.py and run_cts_gf_tests.py (with an option), but this new option is easier.

gfauto: add fuzz --update_ignored_crash_signatures

---

gfauto/.idea/inspectionProfiles/profiles_settings.xml
gfauto/gfauto/cov_util.py

Each stdout line from gcov is a JSON object; do not try to parse entire output as JSON, as this will fail. Make stderr from gcov visible to user.
Rename variables gcda->gcno.
Fix PyCharm profile setting.

gfauto_cov: fix gcc 9+ support again

---

.github/workflows/gfauto.sh
gfauto/README.md
gfauto/dev_shell.sh.template

Remove `--no-warn-script-location` from pip invocation, as older versions of pip may not have this. Assume `python3` instead of `python3.6`, as this is more likely to work.

gfauto: improve dev_shell.sh

---

gfauto/gfauto/signature_util.py

Improve the regex for catchsegv backtraces to help avoid "no_signature".

gfauto: catchsegv backtrace signature improvement

---

gfauto/gfauto/add_amber_tests_to_cts.py

Removed `vk-default-no-waivers.txt` from MUST_PASS_PATHS as the file has been removed from cts and can't be modified anymore.

Remove vk-default-no-waivers.tx from mustpass paths

---

reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/FlattenControlFlowReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/InlineInitializerReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/InlineUniformReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/LoopLimiterImpactChecker.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunitiesBase.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/SimplifyExprReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/StmtReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/VariableDeclReductionOpportunities.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/StmtReductionOpportunitiesTest.java
util/src/main/java/com/graphicsfuzz/util/Constants.java

This change teaches the reducer when a loop limiter is not actually
used to limit any loop, in which case uses of the loop limiter can be
safely removed or simplified.
This is achieved by extracting existing functionality for analysing
loop limiters into its own class, so that it provides functions that
can be queried from multiple ReductionOpportunities classes.
In the process, static helper functions to test whether variable names
are live variables or loop limiters have been moved into the Constants
helper class, where the prefixes for live variables and loop limiters
are defined.
Fixes #950.

Clean up redundant loop limiter uses in the reducer

---

gfauto/gfauto/devices_util.py

Disable SPIR-V validation in the default LLPC configuration, as we validate shaders using a more recent version of spirv-val and we may also have extra spirv-val arguments. Thus, LLPC SPIR-V validation errors are not interesting.

gfauto: change default llpc config

---

gfauto/gfauto/signature_util.py
gfauto/gfautotests/test_signature_util.py

Improve signatures for catchsegv backtraces. Skip libc stack frames. Fix so that module offset includes numbers. Fix so that if a module cannot be found (for passing to addr2line), we can still use the module name and its offset. Add some tests. Show verbose details when running addr2line.

gfauto: improve backtrace signatures

---

gfauto/gfauto/amber_converter.py
gfauto/whitelist.dic

The AmberScript generated from a compute shader job always had a binding location of 0. Now, it uses the binding location from the JSON.
Also add some missing words from the whitelist.dic file.

gfauto: fix SSBO binding

---

experiments/demoChecker.sh

It runs all the demo binaries built in `experiments` directory and logs the resulting return codes in a file in the current working directory.

Add demoChecker to run all demos and log return codes

---

experiments/build-Imagination_Vulkan.sh
experiments/build-Khronos_Samples_Vulkan.sh
experiments/build-SaschaWillems_Vulkan.sh
experiments/build-google_vulkan_test_applications.sh
experiments/build-project.sh
experiments/build-swiftshader-coverage.sh

This PR replaces the shebang in the build scripts with `#!/usr/bin/env bash`. This change removes any assumptions about the location of the bash executable.

Replace the bash shebang with `#!/usr/bin/env bash`

---

.github/workflows/gfauto.sh
.github/workflows/gfauto.yml
gfauto/Pipfile.lock
gfauto/README.md
gfauto/dev_shell.sh.template
gfauto/gfauto/amber_converter.py
gfauto/gfauto/android_device.py
gfauto/gfauto/binaries_util.py
gfauto/gfauto/cov_util.py
gfauto/gfauto/fuzz.py
gfauto/gfauto/fuzz_glsl_test.py
gfauto/gfauto/recipe_wrap.py
gfauto/gfauto/subprocess_util.py
gfauto/gfauto/tool.py
gfauto/gfauto/util.py
gfauto/setup.py

Set `PIPENV_PYTHON` in `dev_shell.sh.template`: In some cases it seems that pipenv will NOT recognize the Python version that is being used, and so pipenv will create a virtual environment using some other version of Python. This line ensures the virtual environment created uses the correct Python binary. This was previously causing Windows CI to fail.
Switch to using the `dataclasses` package, which is a back port of the Python 3.7 dataclasses feature. We were previously using `attr` package.
Re-generate Pipfile.lock so that we get the dataclasses package and updated versions of all other dependencies. 
Fix new lint errors.
Update instructions.

gfauto: fix and update dev dependencies

---

gfauto/gfauto/reduce_source_dir.py

Add --literals_to_uniforms to the `gfauto_reduce_source_dir` command. This runs glsl-reduce with the --literals-to-uniforms flag.

gfauto: add --literals_to_uniforms

---

gfauto/gfauto/binaries_util.py
gfauto/gfauto/common.proto

Allow specifying the path of a binary (e.g. in settings.json and test.json) for testing purposes.

gfauto: allow binary path override

---

.gitignore
server-thrift-gen/pom.xml

`javax.annotation` was removed in Java 11.

Update Java 11 dependencies

---

gfauto/gfauto/binaries_util.py
gfauto/gfauto/fuzz.py
gfauto/gfauto/fuzz_glsl_test.py
gfauto/gfauto/fuzz_spirv_test.py
gfauto/gfauto/spirv_fuzz_util.py

When creating the summary of a crash bug derived from a `stable_` shader, `reduction_1/` will contain a "wrong image" test that exposes the bug. In this case, we now add a `variant_2` shader that is the same as the variant shader, but with the last transformation removed. This is likely to give a shader that is very similar to the variant but does not trigger the bug. The `variant_2` shader is created using the `--replay-range` option of spirv-fuzz.

gfauto: generate variant_2

---

reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/InlineInitializerReductionOpportunities.java
tester/src/test/java/com/graphicsfuzz/tester/GeneratorUnitTest.java

In line with:
https://source.android.com/setup/contribute/respectful-code
this change uses the terms 'exclude' or 'exlusion list' where
'blacklist' was previously used.

Avoid use of 'blacklist' in the code base

---

gfauto/gfauto/spirv_fuzz_util.py

When running spirv-fuzz, use `--fuzzer-pass-validation` to detect validation errors after each fuzzer pass (i.e. spirv-fuzz bugs).

gfauto: use --fuzzer-pass-validation

---

graphicsfuzz/src/main/scripts/examples/glsl-reduce-walkthrough/colorgrid_modulo.frag
graphicsfuzz/src/main/scripts/examples/glsl-reduce-walkthrough/colorgrid_modulo.json
reducer/src/main/java/com/graphicsfuzz/reducer/ReductionDriver.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/LiteralToUniformReductionOpportunity.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/LiteralToUniformReductionOpportunitiesTest.java

The LiteralToUniformReductionOpportunity adds new uniforms to a shader
job.  It should not provide these uniforms with bindings -- it is up
to the reducer to add bindings if they are deemed necessary, right
before emitting the shader as a text file.
This change fixes that issue.  However, it turns out that the reducer
was not adding bindings in the case that no uniforms were present in
the first place -- it was treating a uniform-free shader as a
non-Vulkan shader.  As a temporary workaround, a uniform-free shader
is now treated by the reducer as a Vulkan shader so that if uniforms
are then created, they get bindings when written out as text files.
Related issue to fix this more elegantly in the long-run: #1046.

Do not add bindings LiteralToUniformReductionOpportunity

---

common/src/main/java/com/graphicsfuzz/common/util/PipelineInfo.java
common/src/main/java/com/graphicsfuzz/common/util/PruneUniforms.java
common/src/test/java/com/graphicsfuzz/common/util/PipelineInfoTest.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/LiteralToUniformReductionOpportunity.java

PipelineInfo provides a method for getting the numeric arguments for a
uniform.  This previously returned a list of type Number.  It turned
out that the JSON library backing PipelineInfo might sometimes
represent numeric values using non-standard subclasses of Number - in
particular LazilyParsedNumber.
To guard against this, numeric arguments are now provided as strings.
We always know the types of uniform variables, so can interpret these
strings as integers or floats accordingly.
Fixes #1054.

Provide uniform arguments as strings

---

gfauto/gfauto/signature_util.py
gfauto/gfautotests/test_signature_util.py

Recent testing using LLPC shows that the format of fatal errors has
changed slightly.  This PR relaxes the regex used to recognize fatal
errors to tolerate their old form and their new form.  The same
relaxation is applied for machine code errors to account for the
possibility of an analogous formatting change being applied there.
Some tests are added related to this.

Fix LLVM signature recognition

---

gfauto/gfauto/signature_util.py
gfauto/gfautotests/test_signature_util.py

Adds basic recognition of AddressSanitizer signatures to gfauto, and
adds a test for assertion-related signatures.

Add signature recognition for AddressSanitizer

---

ast/src/main/java/com/graphicsfuzz/common/tool/PrettyPrinterVisitor.java
ast/src/test/java/com/graphicsfuzz/common/tool/PrettyPrinterVisitorTest.java

Improves the pretty printer by writing straight to a print stream
rather than using many intermediate strings.

Avoid string concatenation in pretty printer

---

generator/src/main/java/com/graphicsfuzz/generator/fuzzer/Fuzzer.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateCodeTransformation.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateLiveCodeTransformation.java
generator/src/test/java/com/graphicsfuzz/generator/transformation/DonateDeadCodeTransformationTest.java

To reduce the chances of undefined behaviour, this change forces all
variables to be initialized before a module is donated.
An existing test is fixed in the process; its brokenness was exposed
by this change.
Fixes #1063.

Always initialize variables during donation

---

shaders/src/main/glsl/samples/320es/stable_sampler_boxfilter.frag
shaders/src/main/glsl/samples/320es/stable_sampler_boxfilter.json
shaders/src/main/glsl/samples/320es/stable_sampler_loop.frag
shaders/src/main/glsl/samples/320es/stable_sampler_loop.json
shaders/src/main/glsl/samples/320es/stable_sampler_minimal.frag
shaders/src/main/glsl/samples/320es/stable_sampler_minimal.json
shaders/src/main/glsl/samples/320es/stable_sampler_mip.frag
shaders/src/main/glsl/samples/320es/stable_sampler_mip.json
shaders/src/main/glsl/samples/320es/stable_sampler_polar_simple.frag
shaders/src/main/glsl/samples/320es/stable_sampler_polar_simple.json
shaders/src/main/glsl/samples/320es/stable_sampler_polar_warp.frag
shaders/src/main/glsl/samples/320es/stable_sampler_polar_warp.json
shaders/src/main/glsl/samples/320es/stable_sampler_reuse.frag
shaders/src/main/glsl/samples/320es/stable_sampler_reuse.json
shaders/src/main/glsl/samples/320es/stable_sampler_trace.frag
shaders/src/main/glsl/samples/320es/stable_sampler_trace.json

The samplers range from very simple texture reads to
shaders that read textures based on texture reads, and
various UV coordinate transformations.

Add collection of stable shaders using samplers

---

generator/src/main/java/com/graphicsfuzz/generator/fuzzer/Templates.java
generator/src/main/java/com/graphicsfuzz/generator/util/GenerationParams.java
shaders/src/main/glsl/samples/320es/stable_sampler_boxfilter.frag
shaders/src/main/glsl/samples/320es/stable_sampler_trace.frag

This change enables the disabled comma operator fuzzing and
also removes the unused code that could be used to disable
the use of non-rectangular matrices.

Enable comma operator fuzzing, cleanup

---

gfauto/gfauto/fuzz.py
gfauto/gfauto/fuzz_spirv_test.py

Adds support for different donors and references when using SPIR-V fuzz. These should be placed in spirv_fuzz_donors/ and spirv_fuzz_references/, respectively.

gfauto: support SPIR-V donors and references

---

gfauto/gfauto/android_device.py
gfauto/whitelist.dic

Run Amber to create the Amber cache directory on /sdcard. This might be necessary on newer Android versions to ensure the cache directory is accessible by the Amber app.

gfauto: improve Android permissions

---

gfauto/gfauto/amber_converter.py
gfauto/gfauto/download_cts_gf_tests.py
gfauto/whitelist.dic

...when extracting SPIRV-ASM shaders from an AmberScript file.

gfauto: require TARGET_ENV

---

gfauto/gfauto/bucket_via_transformations.py
gfauto/setup.py

By default, puts spirv-fuzz bad image bugs in buckets classified by the important transformation types that remain.

gfauto: add bucket_via_transformations

---

gfauto/gfauto/cov_from_gcov.py
gfauto/gfauto/cov_util.py

I added a new option: --gcov_functions to generate instead of line coverage, the function coverage when using JSON format. I did testing to check that without the new flag, the tool still generates line coverage, and with the new flag, the tool generates function coverage.

cov: add function coverage option

---

build/travis/check_headers.py
generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateLiveCodeTransformation.java
generator/src/test/java/com/graphicsfuzz/generator/transformation/DonateLiveCodeTransformationTest.java
generator/src/test/java/com/graphicsfuzz/generator/util/RemoveDiscardStatementsTest.java

Removes discard statements from a donor during live code donation, instead of only removing discards from the statements that get locally donated.  This avoids roblems where a donated statement calls a function that contains a discard.
Some tests are also refactored.
Fixes #1110.

Avoid discard in live-donated code

---

gfauto/docs/coverage.md
gfauto/gfauto/cov_from_gcov.py
gfauto/gfauto/cov_util.py

In cov_from_gcov.py, change command line arg "gcov_prefix_dir" to an optional arg "--gcov_prefix_dir". If provided then we proceed as before:
- in gcov_prefix_dir, create symlinks to all .gcno files from the build directory
- iterate over all .gcno files in gcov_prefix_dir
If not provided then we just iterate over all .gcno files in the build directory.

cov: make gcov_prefix_dir optional

---

shaders/src/main/glsl/samples/320es/stable_sampler_polar_simple.frag
shaders/src/main/glsl/samples/320es/stable_sampler_polar_warp.frag

This commit removes a redundant line from stable_sampler_polar_warp.frag
that contained an unused variable.

Remove unused variable from sample shaders

---

shaders/src/main/glsl/samples/320es/linear_algebra_chessboard.frag

This PR implements a sample shader that uses linear algebra instructions.

Add linear algebra chessboard sample shader

---

ast/src/main/antlr4/com/graphicsfuzz/parser/GLSL.g4
ast/src/main/java/com/graphicsfuzz/common/ast/stmt/LoopStmt.java
ast/src/main/java/com/graphicsfuzz/common/ast/visitors/AstBuilder.java
ast/src/test/java/com/graphicsfuzz/common/tool/PrettyPrinterVisitorTest.java
ast/src/test/java/com/graphicsfuzz/common/util/AddBracesTest.java

This change reworks the GLSL grammar to avoid ambiguities in how
if-then-else statements are handled. The approach was inspired by an
Antlr grammar for Java 9. It turns out that if-then-else statements
suffering from the "dangling else" problem were not being parsed as
expected - the change fixes this. The hope is that by avoiding
ambiguity, parsing should be more efficient.

Avoid if-then-else ambiguities in the grammar

---

ast/src/main/java/com/graphicsfuzz/common/ast/type/BasicType.java

Adds new utility functions to return lists of all signed integer based
types (int, ivec2, ivec3, ivec4) and changes the availability of the
boolean utility function.

Add new basic type groups returning functions

---

ast/src/main/java/com/graphicsfuzz/common/typing/Typer.java
ast/src/main/java/com/graphicsfuzz/common/typing/TyperHelper.java
ast/src/test/java/com/graphicsfuzz/common/typing/TyperTest.java

Updates the Typer class to produce a result in the case of assignments
and the TyperHelper class to correctly type shift operations in the
case of left and right scalar types (the resulting type is the one
from the left operand).

Update of the typer with shifts and assignments

---

ast/src/main/java/com/graphicsfuzz/common/ast/decl/InterfaceBlock.java
ast/src/main/java/com/graphicsfuzz/common/tool/PrettyPrinterVisitor.java
ast/src/main/java/com/graphicsfuzz/common/typing/Scope.java
ast/src/main/java/com/graphicsfuzz/common/typing/ScopeEntry.java
ast/src/main/java/com/graphicsfuzz/common/typing/ScopeTrackingVisitor.java
ast/src/main/java/com/graphicsfuzz/common/typing/Typer.java
generator/src/main/java/com/graphicsfuzz/generator/fuzzer/FuzzingContext.java
generator/src/main/java/com/graphicsfuzz/generator/semanticspreserving/AddSwitchMutation.java
generator/src/main/java/com/graphicsfuzz/generator/transformation/DonateCodeTransformation.java
generator/src/test/java/com/graphicsfuzz/generator/semanticspreserving/OutlineStatementMutationTest.java
generator/src/test/java/com/graphicsfuzz/generator/transformation/injection/InjectionPointTest.java
reducer/src/main/java/com/graphicsfuzz/reducer/ReductionDriver.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/IReductionOpportunityFinder.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/InterfaceBlockReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/InterfaceBlockReductionOpportunity.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunities.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/InterfaceBlockReductionOpportunitiesTest.java

Adds functionality to the reducer to eliminate interface blocks that
are not used. This involved adding support for tracking interface
blocks in the ScopeTrackingVisitor, and some minor changes to the
internals of InterfaceBlock were made in the process.
Fixes #1162.

Reducer: remove unused interface blocks

---

reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/VariableDeclReductionOpportunities.java

Since adding support for interface blocks, we need to check that a
global-scope declaration really does refer to a variable group.

Fix bug to do with reducing global variables

---

tester/src/test/java/com/graphicsfuzz/tester/GeneratorUnitTest.java

This caused tests to be run twice.

Remove duplicate line from GeneratorUnitTest

---

gfauto/gfauto/add_amber_tests_to_cts.py

The directories containing mustpass files in CTS were renamed from
"master" to "main". This commit changes add_amber_tests_to_cts.py
to look up the mustpass files in the proper directories.

gfauto: Update add_amber_tests_to_cts.py

---

reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/CompoundExprToSubExprReductionOpportunities.java
reducer/src/main/java/com/graphicsfuzz/reducer/reductionopportunities/ReductionOpportunitiesBase.java
reducer/src/test/java/com/graphicsfuzz/reducer/ReductionDriverTest.java
reducer/src/test/java/com/graphicsfuzz/reducer/reductionopportunities/CompoundExprToSubExprReductionOpportunitiesTest.java

Improves the reducer's ability to reduce array indexing expressions,
by being less conservative about l-values.
Part of #1179.

Better reduction for array indices
